extends Node


func _ready()->void:
	call_deferred("_run")


func _run()->void:
	GameState.reset_for_new_world(90210)
	GameState.initialize_citizen_registry()
	GameState.resource_stockpiles={"Timber":100.0,"Stone":100.0,"Fiber Plants":100.0,"Iron Ore":100.0,"Food":1000.0}
	MilitaryCampaign.reset_for_new_world()
	var locked_spear:Dictionary=MilitaryCampaign.queue_equipment_production("spear",1)
	assert(String(locked_spear.get("required_discovery",""))=="hafted_weapons")
	var locked_line:Dictionary=MilitaryCampaign.start_training("line_infantry","improvised",1)
	assert(String(locked_line.get("required_discovery",""))=="shield_wall")
	var raised:Dictionary=MilitaryCampaign.raise_recruits(12)
	var raised_count:=int(raised.raised)
	assert(raised_count>0)
	assert(raised_count<=int(raised.capacity))
	var production:Dictionary=MilitaryCampaign.queue_equipment_production("improvised",raised_count)
	assert(not production.has("error"))
	var training:Dictionary=MilitaryCampaign.start_training("levy","improvised",raised_count)
	assert(int(training.accepted)==raised_count)
	for day in 14: MilitaryCampaign._process_military_day()
	var army:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(army.troops)==raised_count)
	assert(int(army.formations[0].equipment)==raised_count)
	assert(int(army.recruits)==0)
	assert((army.training_queue as Array).is_empty())
	assert((army.equipment_queue as Array).is_empty())
	GameState.known_discoveries.append("hafted_weapons")
	GameState.discovery_adoption["hafted_weapons"]=0.20
	var unlocked_spear:Dictionary=MilitaryCampaign.queue_equipment_production("spear",1)
	assert(not unlocked_spear.has("error"))
	var capabilities:Dictionary=MilitaryCampaign.military_capabilities()
	assert(bool(capabilities.equipment.spear.unlocked))
	assert(not bool(capabilities.units.line_infantry.unlocked))
	var enemy:Dictionary=MilitaryCampaign.simulator.create_formation_force("Raiders",[{"unit":"levy","weapon":"improvised","count":8,"equipment":8}],0.7,0.8)
	var battle:Dictionary=MilitaryCampaign.resolve_campaign_battle(enemy,{"seed":77,"max_rounds":2})
	assert(not battle.has("error"))
	var post_battle:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(post_battle.troops)==(post_battle.soldier_ids as Array).size())
	for day in 20: MilitaryCampaign._process_military_day()
	var recovered:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(recovered.troops)==(recovered.soldier_ids as Array).size())
	assert(int(recovered.wounded_pool)==(recovered.wounded_ids as Array).size())
	assert(int(recovered.scattered_pool)==(recovered.scattered_ids as Array).size())
	var before_capture:=int(recovered.troops)
	MilitaryCampaign._mark_home_prisoners(1)
	var captured:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(captured.troops)==before_capture-1)
	assert(int(captured.troops)==(captured.soldier_ids as Array).size())
	assert((captured.captured_ids as Array).size()==1)
	print("MILITARY_CAMPAIGN_PROBE raised=%d trained=%d equipped=%d battle=%s" % [raised.raised,army.troops,army.formations[0].equipment,battle.outcome])
	get_tree().quit()
