extends Node


func _ready()->void:
	call_deferred("_run")


func _run()->void:
	GameState.reset_for_new_world(90210)
	GameState.initialize_citizen_registry()
	GameState.resource_stockpiles={"Timber":100.0,"Stone":100.0,"Fiber Plants":100.0,"Iron Ore":100.0,"Food":1000.0}
	MilitaryCampaign.reset_for_new_world()
	var locked_spear:Dictionary=MilitaryCampaign.queue_equipment_production("spear",1)
	assert(String(locked_spear.get("required_discovery",""))=="hafted_weapons")
	var locked_line:Dictionary=MilitaryCampaign.start_training("line_infantry","improvised",1)
	assert(String(locked_line.get("required_discovery",""))=="shield_wall")
	var raised:Dictionary=MilitaryCampaign.raise_recruits(12)
	var raised_count:=int(raised.raised)
	assert(raised_count>0)
	assert(raised_count<=int(raised.capacity))
	var production:Dictionary=MilitaryCampaign.queue_equipment_production("improvised",raised_count)
	assert(not production.has("error"))
	var training:Dictionary=MilitaryCampaign.start_training("levy","improvised",raised_count)
	assert(int(training.accepted)==raised_count)
	for day in 14: MilitaryCampaign._process_military_day()
	var army:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(army.troops)==raised_count)
	assert(int(army.formations[0].equipment)==raised_count)
	assert(float(army.formations[0].training)<1.0)
	assert(float(army.readiness)>0.0 and float(army.readiness)<=1.0)
	assert((army.readiness_components as Dictionary).has("condition"))
	assert(int(army.recruits)==0)
	assert((army.training_queue as Array).is_empty())
	assert((army.equipment_queue as Array).is_empty())
	GameState.known_discoveries.append("hafted_weapons")
	GameState.discovery_adoption["hafted_weapons"]=0.20
	var basic_training_quality:=MilitaryCampaign._training_quality("line_infantry")
	GameState.known_discoveries.append_array(["formation_drill","professional_corps"])
	GameState.discovery_adoption["formation_drill"]=0.80
	GameState.discovery_adoption["professional_corps"]=0.70
	assert(MilitaryCampaign._training_quality("line_infantry")>basic_training_quality)
	var unlocked_spear:Dictionary=MilitaryCampaign.queue_equipment_production("spear",1)
	assert(not unlocked_spear.has("error"))
	var capabilities:Dictionary=MilitaryCampaign.military_capabilities()
	assert(bool(capabilities.equipment.spear.unlocked))
	assert(not bool(capabilities.units.line_infantry.unlocked))
	var bronze_recipe:Dictionary=MilitaryCampaign._equipment_recipe("sword_shield")
	assert(bronze_recipe.materials.has("Copper Ore"))
	assert(bronze_recipe.materials.has("Tin Ore"))
	assert(not bronze_recipe.materials.has("Iron Ore"))
	var low_training:Dictionary=MilitaryCampaign.simulator.create_formation_force("Low",[{"unit":"line_infantry","weapon":"spear","count":10,"equipment":10,"training":0.30}],1.0,1.0)
	var high_training:Dictionary=MilitaryCampaign.simulator.create_formation_force("High",[{"unit":"line_infantry","weapon":"spear","count":10,"equipment":10,"training":1.10}],1.0,1.0)
	var dummy:Dictionary=MilitaryCampaign.simulator.create_formation_force("Dummy",[{"unit":"levy","weapon":"improvised","count":10,"equipment":10}],1.0,1.0)
	assert(float(MilitaryCampaign.simulator.evaluate_force(high_training,dummy)[0].attack)>float(MilitaryCampaign.simulator.evaluate_force(low_training,dummy)[0].attack))
	var enemy:Dictionary=MilitaryCampaign.simulator.create_formation_force("Raiders",[{"unit":"levy","weapon":"improvised","count":8,"equipment":8}],0.7,0.8)
	var battle:Dictionary=MilitaryCampaign.resolve_campaign_battle(enemy,{"seed":77,"max_rounds":2})
	assert(not battle.has("error"))
	var post_battle:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(post_battle.troops)==(post_battle.soldier_ids as Array).size())
	for day in 20: MilitaryCampaign._process_military_day()
	var recovered:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(recovered.troops)==(recovered.soldier_ids as Array).size())
	assert(int(recovered.wounded_pool)==(recovered.wounded_ids as Array).size())
	assert(int(recovered.scattered_pool)==(recovered.scattered_ids as Array).size())
	var before_capture:=int(recovered.troops)
	MilitaryCampaign._mark_home_prisoners(1)
	var captured:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(captured.troops)==before_capture-1)
	assert(int(captured.troops)==(captured.soldier_ids as Array).size())
	assert((captured.captured_ids as Array).size()==1)
	assert(MilitaryCampaign.validate_state().is_empty())
	var saved:Dictionary=MilitaryCampaign.export_state()
	MilitaryCampaign.reset_for_new_world()
	var restored:Dictionary=MilitaryCampaign.import_state(saved)
	assert(bool(restored.get("ok",false)))
	var restored_army:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(restored_army.troops)==int(captured.troops))
	assert((restored_army.captured_ids as Array)==(captured.captured_ids as Array))
	var invalid:=saved.duplicate(true)
	if not (invalid.home_army.soldier_ids as Array).is_empty(): invalid.home_army.wounded_ids.append(invalid.home_army.soldier_ids[0])
	var rejected:Dictionary=MilitaryCampaign.import_state(invalid)
	assert(rejected.has("error"))
	assert(MilitaryCampaign.validate_state().is_empty())
	var marshal_citizen:Dictionary={}
	for citizen in GameState.living_citizens():
		if int(citizen.id) not in (MilitaryCampaign.home_army.soldier_ids as Array) and int(citizen.id) not in (MilitaryCampaign.home_army.captured_ids as Array): marshal_citizen=citizen; break
	assert(not marshal_citizen.is_empty())
	var marshal_record:={"citizen_id":int(marshal_citizen.id),"name":String(marshal_citizen.name),"courage":0.72,"suspicion":0.64,"honesty":0.61,"pride":0.55,"skills":{"Strategy":72,"Tactics":68,"Logistics":58},"relationships":{"sovereign":{"trust":0.5,"respect":0.5,"fear":0.1,"resentment":0.0,"obligation":0.5}}}
	GameState.leadership_positions["Marshal"]=marshal_record
	MilitaryCampaign.home_army["commander"]=MilitaryCampaign._marshal_commander()
	MilitaryCampaign._apply_home_commander_fate({"defeated":MilitaryCampaign.home_army.name,"commander_fate":"killed"})
	assert(not bool(GameState.citizen_by_id(int(marshal_citizen.id)).alive))
	assert(GameState.leadership_positions.has("Marshal"))
	assert(int(GameState.leadership_positions.Marshal.citizen_id)!=int(marshal_citizen.id))
	assert(bool(MilitaryCampaign.home_army.commander.get("acting",false)))
	print("MILITARY_CAMPAIGN_PROBE raised=%d trained=%d equipped=%d battle=%s" % [raised.raised,army.troops,army.formations[0].equipment,battle.outcome])
	get_tree().quit()
