extends Node


func _ready()->void:
	call_deferred("_run")


func _run()->void:
	GameState.reset_for_new_world(90210)
	GameState.initialize_citizen_registry()
	GameState.population_allocations["Crafting"]=6
	GameState.population_allocations["Logistics"]=4
	GameState.resource_stockpiles={"Timber":100.0,"Stone":100.0,"Fiber Plants":100.0,"Iron Ore":100.0,"Food":1000.0}
	MilitaryCampaign.reset_for_new_world()
	var locked_spear:Dictionary=MilitaryCampaign.queue_equipment_production("spear",1)
	assert(String(locked_spear.get("required_discovery",""))=="hafted_weapons")
	var locked_line:Dictionary=MilitaryCampaign.start_training("line_infantry","improvised",1)
	assert(String(locked_line.get("required_discovery",""))=="shield_wall")
	var impossible_cavalry:Dictionary=MilitaryCampaign.start_training("cavalry","lance",1)
	assert(String(impossible_cavalry.get("error","")).contains("domesticated mount"))
	assert(String(MilitaryCampaign.military_capabilities().units.cavalry.get("physical_requirement",""))=="domesticated_mounts")
	var raised:Dictionary=MilitaryCampaign.raise_recruits(12)
	var raised_count:=int(raised.raised)
	assert(raised_count>0)
	assert(raised_count<=int(raised.capacity))
	var production:Dictionary=MilitaryCampaign.queue_equipment_production("improvised",raised_count)
	assert(not production.has("error"))
	var training:Dictionary=MilitaryCampaign.start_training("levy","improvised",raised_count)
	assert(int(training.accepted)==raised_count)
	MilitaryCampaign._process_military_day()
	assert(int(MilitaryCampaign.military_inventory.improvised)>0)
	assert(int(MilitaryCampaign.military_inventory.improvised)<raised_count)
	var partial_training:=float(GameState.citizen_by_id(int(MilitaryCampaign.training_queue[0].soldier_ids[0])).get("military_training",0.0))
	assert(partial_training>0.0)
	var cancelled:Dictionary=MilitaryCampaign.cancel_training(int(training.id))
	assert(int(cancelled.returned)==raised_count)
	assert(MilitaryCampaign.training_queue.is_empty())
	training=MilitaryCampaign.start_training("levy","improvised",raised_count)
	assert(int(training.accepted)==raised_count)
	assert(float(training.required_days)<7.0)
	for day in 13: MilitaryCampaign._process_military_day()
	var army:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(army.troops)==raised_count)
	assert(int(army.formations[0].equipment)==raised_count)
	assert(int(army.formations[0].id)>0)
	assert(float(army.formations[0].training)<1.0)
	assert(float(army.readiness)>0.0 and float(army.readiness)<=1.0)
	assert((army.readiness_components as Dictionary).has("condition"))
	MilitaryCampaign.home_army.formations[0]["wear_accumulator"]=0.99
	MilitaryCampaign.home_army["recent_combat_days"]=7
	var damaged_before:=int(MilitaryCampaign.damaged_equipment.improvised)
	MilitaryCampaign._process_equipment_wear_day()
	assert(int(MilitaryCampaign.damaged_equipment.improvised)==damaged_before+1)
	var repair:Dictionary=MilitaryCampaign.queue_equipment_repair("improvised",1)
	assert(not repair.has("error"))
	for day in 3: MilitaryCampaign._process_equipment_production_day()
	assert(int(MilitaryCampaign.military_inventory.improvised)==1)
	assert(MilitaryCampaign._deliver_inventory_replacements(1)==1)
	assert(int(army.recruits)==0)
	assert(int(army.reserve_manpower)==0)
	assert(MilitaryCampaign._mobilized_count()==raised_count)
	assert((army.training_queue as Array).is_empty())
	assert((army.equipment_queue as Array).is_empty())
	GameState.known_discoveries.append("hafted_weapons")
	GameState.discovery_adoption["hafted_weapons"]=0.20
	var basic_training_quality:=MilitaryCampaign._training_quality("line_infantry")
	GameState.known_discoveries.append_array(["formation_drill","professional_corps"])
	GameState.discovery_adoption["formation_drill"]=0.80
	GameState.discovery_adoption["professional_corps"]=0.70
	assert(MilitaryCampaign._training_quality("line_infantry")>basic_training_quality)
	var unlocked_spear:Dictionary=MilitaryCampaign.queue_equipment_production("spear",1)
	assert(not unlocked_spear.has("error"))
	var capabilities:Dictionary=MilitaryCampaign.military_capabilities()
	assert(bool(capabilities.equipment.spear.unlocked))
	assert(not bool(capabilities.units.line_infantry.unlocked))
	var bronze_recipe:Dictionary=MilitaryCampaign._equipment_recipe("sword_shield")
	assert(bronze_recipe.materials.has("Copper Ore"))
	assert(bronze_recipe.materials.has("Tin Ore"))
	assert(not bronze_recipe.materials.has("Iron Ore"))
	var low_training:Dictionary=MilitaryCampaign.simulator.create_formation_force("Low",[{"unit":"line_infantry","weapon":"spear","count":10,"equipment":10,"training":0.30}],1.0,1.0)
	var high_training:Dictionary=MilitaryCampaign.simulator.create_formation_force("High",[{"unit":"line_infantry","weapon":"spear","count":10,"equipment":10,"training":1.10}],1.0,1.0)
	var dummy:Dictionary=MilitaryCampaign.simulator.create_formation_force("Dummy",[{"unit":"levy","weapon":"improvised","count":10,"equipment":10}],1.0,1.0)
	assert(float(MilitaryCampaign.simulator.evaluate_force(high_training,dummy)[0].attack)>float(MilitaryCampaign.simulator.evaluate_force(low_training,dummy)[0].attack))
	var green_force:Dictionary=MilitaryCampaign.simulator.create_formation_force("Green",[{"unit":"line_infantry","weapon":"spear","count":10,"equipment":10,"training":0.70,"experience":0.0}],1.0,1.0)
	var veteran_force:Dictionary=MilitaryCampaign.simulator.create_formation_force("Veteran",[{"unit":"line_infantry","weapon":"spear","count":10,"equipment":10,"training":0.70,"experience":0.80}],1.0,1.0)
	assert(float(MilitaryCampaign.simulator.evaluate_force(veteran_force,dummy)[0].attack)>float(MilitaryCampaign.simulator.evaluate_force(green_force,dummy)[0].attack))
	var enemy:Dictionary=MilitaryCampaign.simulator.create_formation_force("Raiders",[{"unit":"levy","weapon":"improvised","count":8,"equipment":8}],0.7,0.8)
	var battle:Dictionary=MilitaryCampaign.resolve_campaign_battle(enemy,{"seed":77,"max_rounds":2})
	assert(not battle.has("error"))
	var post_battle:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(post_battle.troops)==(post_battle.soldier_ids as Array).size())
	if not (post_battle.soldier_ids as Array).is_empty():
		var veteran_id:=int(post_battle.soldier_ids[0])
		var veteran:Dictionary=GameState.citizen_by_id(veteran_id)
		assert(float(veteran.get("military_experience",0.0))>0.0)
		assert(int(veteran.get("battles_survived",0))==1)
		var veteran_experience:=float(veteran.military_experience)
		var veteran_quality:=MilitaryCampaign._training_quality("line_infantry",[veteran_id])
		veteran["military_experience"]=0.0
		var novice_quality:=MilitaryCampaign._training_quality("line_infantry",[veteran_id])
		veteran["military_experience"]=veteran_experience
		MilitaryCampaign._refresh_formation_experience()
		assert(veteran_quality>novice_quality)
	if not MilitaryCampaign.pending_aftermath.is_empty():
		var aftermath:Dictionary=MilitaryCampaign.resolve_aftermath("hold","army stores","hold")
		assert(not aftermath.has("error"))
	for day in 20: MilitaryCampaign._process_military_day()
	var recovered:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(recovered.troops)==(recovered.soldier_ids as Array).size())
	assert(int(recovered.wounded_pool)==(recovered.wounded_ids as Array).size())
	assert(int(recovered.scattered_pool)==(recovered.scattered_ids as Array).size())
	var before_capture:=int(recovered.troops)
	MilitaryCampaign._mark_home_prisoners(1)
	var captured:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(captured.troops)==before_capture-1)
	assert(int(captured.troops)==(captured.soldier_ids as Array).size())
	assert((captured.captured_ids as Array).size()==1)
	assert(MilitaryCampaign._mobilized_count()==raised_count)
	var open_capacity:=maxi(0,MilitaryCampaign.recruitment_capacity()-MilitaryCampaign._mobilized_count())
	var capped_replacement:Dictionary=MilitaryCampaign.raise_recruits(raised_count)
	assert(int(capped_replacement.raised)==mini(raised_count,open_capacity))
	if not MilitaryCampaign.recruit_pool.is_empty():
		var injury_order:Dictionary=MilitaryCampaign.start_training("levy","improvised",1)
		assert(not injury_order.has("error"))
		MilitaryCampaign.training_queue[-1]["injury_accumulator"]=1.0
		MilitaryCampaign._process_training_day()
		assert(MilitaryCampaign.training_injuries.size()==1)
		var injured_id:=int(MilitaryCampaign.training_injuries[0].citizen_id)
		assert(String(GameState.citizen_by_id(injured_id).army_status)=="training_injured")
		for day in 13: MilitaryCampaign._process_training_injuries_day()
		assert(injured_id in MilitaryCampaign.recruit_pool)
	var target_id:=int(MilitaryCampaign.home_army.formations[0].id)
	var veteran_cohort_experience:=float(MilitaryCampaign.home_army.formations[0].experience)
	var reinforcement:Dictionary=MilitaryCampaign.reinforce_formation(target_id,raised_count)
	if not reinforcement.has("error"):
		for day in 20: MilitaryCampaign._process_training_day()
		var reinforced_index:=MilitaryCampaign._formation_index(target_id)
		assert(reinforced_index>=0)
		assert(float(MilitaryCampaign.home_army.formations[reinforced_index].experience)<=veteran_cohort_experience)
	captured=MilitaryCampaign.campaign_army_snapshot()
	assert(MilitaryCampaign.validate_state().is_empty())
	var saved:Dictionary=MilitaryCampaign.export_state()
	MilitaryCampaign.reset_for_new_world()
	var restored:Dictionary=MilitaryCampaign.import_state(saved)
	assert(bool(restored.get("ok",false)))
	var restored_army:Dictionary=MilitaryCampaign.campaign_army_snapshot()
	assert(int(restored_army.troops)==int(captured.troops))
	assert((restored_army.captured_ids as Array)==(captured.captured_ids as Array))
	var legacy:=saved.duplicate(true)
	legacy["version"]=1
	legacy.erase("next_training_order_id"); legacy.erase("next_formation_id"); legacy.erase("training_injuries")
	for formation in legacy.home_army.formations: formation.erase("id")
	MilitaryCampaign.reset_for_new_world()
	var migrated:Dictionary=MilitaryCampaign.import_state(legacy)
	assert(bool(migrated.get("ok",false)))
	assert(MilitaryCampaign.validate_state().is_empty())
	var invalid:=saved.duplicate(true)
	if not (invalid.home_army.soldier_ids as Array).is_empty(): invalid.home_army.wounded_ids.append(invalid.home_army.soldier_ids[0])
	var rejected:Dictionary=MilitaryCampaign.import_state(invalid)
	assert(rejected.has("error"))
	assert(MilitaryCampaign.validate_state().is_empty())
	var marshal_citizen:Dictionary={}
	for citizen in GameState.living_citizens():
		if int(citizen.id) not in (MilitaryCampaign.home_army.soldier_ids as Array) and int(citizen.id) not in (MilitaryCampaign.home_army.captured_ids as Array): marshal_citizen=citizen; break
	assert(not marshal_citizen.is_empty())
	var marshal_record:={"citizen_id":int(marshal_citizen.id),"name":String(marshal_citizen.name),"courage":0.72,"suspicion":0.64,"honesty":0.61,"pride":0.55,"skills":{"Strategy":72,"Tactics":68,"Logistics":58},"relationships":{"sovereign":{"trust":0.5,"respect":0.5,"fear":0.1,"resentment":0.0,"obligation":0.5}}}
	GameState.leadership_positions["Marshal"]=marshal_record
	MilitaryCampaign.home_army["commander"]=MilitaryCampaign._marshal_commander()
	GameState.known_discoveries.append("shield_wall")
	GameState.discovery_adoption["shield_wall"]=0.80
	var retrain_target:=int(MilitaryCampaign.home_army.formations[0].id)
	var experience_before_retraining:=float(MilitaryCampaign.home_army.formations[0].experience)
	var retraining:Dictionary=MilitaryCampaign.retrain_formation(retrain_target,"line_infantry","spear")
	assert(not retraining.has("error"))
	for day in 55: MilitaryCampaign._process_training_day()
	assert(not MilitaryCampaign.home_army.formations.is_empty())
	assert(String(MilitaryCampaign.home_army.formations[-1].unit)=="line_infantry")
	assert(is_equal_approx(float(MilitaryCampaign.home_army.formations[-1].experience),experience_before_retraining))
	MilitaryCampaign._apply_home_commander_fate({"defeated":MilitaryCampaign.home_army.name,"commander_fate":"killed"})
	assert(not bool(GameState.citizen_by_id(int(marshal_citizen.id)).alive))
	assert(GameState.leadership_positions.has("Marshal"))
	assert(int(GameState.leadership_positions.Marshal.citizen_id)!=int(marshal_citizen.id))
	assert(bool(MilitaryCampaign.home_army.commander.get("acting",false)))
	var before_stand_down:=int(MilitaryCampaign.home_army.troops)
	var experience_before_stand_down:Dictionary={}
	for citizen_id in MilitaryCampaign.home_army.soldier_ids: experience_before_stand_down[int(citizen_id)]=float(GameState.citizen_by_id(int(citizen_id)).get("military_experience",0.0))
	var stood_down:Dictionary=MilitaryCampaign.stand_down(1)
	assert(int(stood_down.released)==1)
	assert(int(MilitaryCampaign.home_army.troops)==before_stand_down-1)
	var released_citizen:Dictionary=GameState.citizen_by_id(int(stood_down.citizen_ids[0]))
	assert(String(released_citizen.army_status)=="civilian")
	assert(is_equal_approx(float(released_citizen.get("military_experience",0.0)),float(experience_before_stand_down[int(released_citizen.id)])))
	assert(MilitaryCampaign.validate_state().is_empty())
	GameState.simulation_metrics["food_intake_ratio"]=0.0
	GameState.population_allocations["Logistics"]=0
	MilitaryCampaign.home_army["supply_level"]=1.0
	MilitaryCampaign._refresh_readiness()
	var supplied_readiness:=float(MilitaryCampaign.home_army.readiness)
	for day in 8: MilitaryCampaign._process_military_day()
	var depleted_supply:=float(MilitaryCampaign.home_army.supply_level)
	var depleted_readiness:=float(MilitaryCampaign.home_army.readiness)
	assert(depleted_supply<0.40)
	assert(depleted_readiness<supplied_readiness)
	GameState.simulation_metrics["food_intake_ratio"]=1.0
	GameState.population_allocations["Logistics"]=10
	for day in 12: MilitaryCampaign._process_military_day()
	assert(float(MilitaryCampaign.home_army.supply_level)>depleted_supply)
	print("MILITARY_CAMPAIGN_PROBE raised=%d trained=%d equipped=%d battle=%s" % [raised.raised,army.troops,army.formations[0].equipment,battle.outcome])
	get_tree().quit()
