extends GdUnitTestSuite
const S=preload("res://scripts/microscopy_samples.gd")
func test_isolation_transfers_finite_named_material_and_never_grants_purity()->void:
	var ledger:=S.empty_state()
	var source:=S.add(ledger,"starter",1,0,"home",0,.04,{"viability":.9,"contamination":.4})
	S.measure(ledger,source,0,false,["microbial_observation"])
	var child:=S.isolate(ledger,source,1)
	assert_float(float(source.amount)+float(child.amount)).is_equal(.04)
	assert_int(int(child.parent)).is_equal(int(source.id))
	assert_float(float(child.contamination)).is_greater(0.0)
	assert_bool(S.valid(ledger)).is_true()
func test_growth_and_time_lapse_require_distinct_days_and_supplied_media()->void:
	var ledger:=S.empty_state()
	var sample:=S.add(ledger,"starter",1,0,"home",0,.04,{"viability":.9,"contamination":.1})
	assert_bool(S.grow(sample,0,.02,true)).is_false()
	assert_bool(S.grow(sample,1,0.0,true)).is_false()
	assert_bool(S.grow(sample,1,.02,true)).is_true()
	var before:=sample.duplicate(true)
	assert_bool(S.grow(sample,1,.02,true)).is_false()
	assert_dict(sample).is_equal(before)
	S.measure(ledger,sample,1,false,["cell_division_observation"])
	assert_bool(sample.methods.has("division")).is_false()
	S.grow(sample,2,.02,true);S.measure(ledger,sample,2,false,["cell_division_observation"])
	assert_bool(sample.methods.has("division")).is_true()
	S.expire(ledger,22)
	assert_array(ledger.specimens).is_empty()
