extends GdUnitTestSuite
const T=preload("res://scripts/metallurgy_thermal_cycle.gd")
func test_heat_budget_and_specimen_capacity_change_actual_temperature()->void:
	var light:=T.start(T.normalizing_program(),1.0)
	var heavy:=T.start(T.normalizing_program(),2.0)
	var stalled:=light.duplicate(true)
	assert_float(float(T.advance(stalled,1,0,0).work)).is_equal(0.0)
	assert_dict(stalled).is_equal(light)
	var paid:=T.advance(light,1,100,0)
	assert_float(float(paid.energy)).is_less_equal(100.000001)
	assert_float(float(paid.work)).is_less_equal(.200001)
	T.advance(heavy,float(paid.work),100,0)
	assert_float(float(light.temperature)).is_greater(float(heavy.temperature))
	assert_float(float(light.temperature)).is_greater(20.0)
func test_normalizing_cycle_retains_hot_exposure_and_air_cools_after_reload()->void:
	var run:=T.start(T.normalizing_program())
	T.advance(run,3.5,3000,0)
	assert_bool(T.complete(run)).is_false()
	assert_float(float(run.temperature)).is_equal_approx(880,.000001)
	var restored:Dictionary=bytes_to_var(var_to_bytes(run))
	assert_bool(T.valid(restored)).is_true()
	var receipt:=T.advance(restored,3.5,3000,0)
	assert_bool(T.complete(restored)).is_true()
	assert_int(restored.trace.size()).is_equal(3)
	assert_float(float(restored.peak)).is_equal_approx(880,.000001)
	assert_float(float(restored.hot_work)).is_greater(1.0)
	assert_float(float(restored.temperature)).is_less(120.0)
	assert_float(float(restored.energy)).is_equal_approx(float(run.energy)+float(receipt.energy),.000001)
	assert_float(float(restored.coolant)).is_equal(0.0)
func test_selected_quench_requires_finite_coolant_and_invalid_progress_is_rejected()->void:
	var program:=T.normalizing_program()
	program[2].loss=3.0;program[2].coolant=2.0
	var run:=T.start(program)
	T.advance(run,4,3000,0)
	assert_int(run.stage).is_equal(2)
	var before:=run.duplicate(true)
	assert_float(float(T.advance(run,1,0,0).work)).is_equal(0.0)
	assert_dict(run).is_equal(before)
	var receipt:=T.advance(run,1,0,.4)
	assert_float(float(receipt.coolant)).is_equal_approx(.4,.000001)
	assert_float(float(receipt.work)).is_equal_approx(.2,.000001)
	assert_float(float(run.temperature)).is_less(float(before.temperature))
	var corrupt:=run.duplicate(true);corrupt.work+=1.0
	assert_bool(T.valid(corrupt)).is_false()
	corrupt=run.duplicate(true);corrupt.trace[0].energy=INF
	assert_bool(T.valid(corrupt)).is_false()

func test_preheating_cannot_replace_the_declared_hold()->void:
	var run:=T.start(T.normalizing_program())
	T.advance(run,3,3000,0)
	assert_float(float(run.hot_work)).is_greater(1.0)
	assert_float(float(run.longest_hold)).is_equal(0.0)
	T.advance(run,.5,3000,0)
	assert_float(float(run.longest_hold)).is_equal_approx(.5,.000001)
	var corrupted:=run.duplicate(true);corrupted.longest_hold=2.0
	assert_bool(T.valid(corrupted)).is_false()
	T.advance(run,.5,3000,0)
	assert_float(float(run.longest_hold)).is_equal_approx(1.0,.000001)
	assert_bool(T.valid(run)).is_true()
