extends RefCounted
## Manufactured batches use the same physical stocks and finite workshop lines
## as equipment. Quantities are game batches, not claims of industrial SI units.
const PRODUCTS={
	"retted_fibers":{"name": "Prepared plant fibers", "output": "Prepared Fibers", "gate": "fiber_retting", "materials": {"Fiber Plants": 2.0, "Freshwater": 2.0}, "days": 3.0, "tooling": {"Clay": 3.0, "Timber": 2.0}},
	"combed_fibers":{"name": "Combed plant fibers", "output": "Combed Fibers", "gate": "fiber_combing", "materials": {"Prepared Fibers": 1.0}, "days": 1.5, "tooling": {"Timber": 2.0, "Stone": 1.0}},
	"spun_yarn":{"name": "Spindle-spun yarn", "output": "Spun Yarn", "gate": "drop_spindles", "materials": {"Prepared Fibers": 1.0}, "days": 3.0, "tooling": {"Clay": 1.0, "Timber": 1.0}},
	"combed_yarn":{"name": "Yarn from combed fibers", "output": "Spun Yarn", "gate": "drop_spindles", "materials": {"Combed Fibers": 0.75}, "days": 2.5, "tooling": {"Clay": 1.0, "Timber": 1.0}},
	"loom_weights":{"name": "Clay loom weights", "output": "Loom Weights", "gate": "warp_weighted_looms", "materials": {"Clay": 1.0, "Timber": 0.5}, "days": 2.0, "tooling": {"Stone": 2.0}},
	"woven_cloth":{"name": "Plain-woven cloth", "output": "Woven Cloth", "gate": "plain_weaving", "materials": {"Spun Yarn": 2.0}, "days": 4.0, "tooling": {"Loom Weights": 2.0, "Timber": 4.0}},
	"woven_dressings":{"name": "Prepared woven dressings", "output": "Woven Dressings", "gate": "woven_dressings", "materials": {"Woven Cloth": 0.2, "Freshwater": 1.0}, "days": 2.0, "tooling": {"Clay": 2.0}},

	"gear_sets":{"name": "Metal gear sets", "output": "Gear Sets", "gate": "gear_ratios", "materials": {"Steel": 2.0}, "days": 5.0, "tooling": {"Steel": 4.0, "Timber": 4.0}},
	"shaft_bearings":{"name": "Shaft bearings", "output": "Shaft Bearings", "gate": "bearing_surfaces", "materials": {"Refined Copper": 1.0, "Steel": 0.5, "Graphite": 0.05}, "days": 4.0, "tooling": {"Steel": 3.0, "Timber": 2.0}},
	"crank_assemblies":{"name": "Crank assemblies", "output": "Crank Assemblies", "gate": "crank_linkages", "materials": {"Steel": 2.0, "Shaft Bearings": 1.0}, "days": 4.0, "tooling": {"Steel": 4.0, "Timber": 3.0}},
	"flywheels":{"name": "Balanced flywheels", "output": "Flywheels", "gate": "flywheel_smoothing", "materials": {"Wrought Iron": 3.0, "Steel": 0.5}, "days": 4.0, "tooling": {"Steel": 3.0, "Stone": 4.0}},
	"mechanical_governors":{"name": "Mechanical governors", "output": "Mechanical Governors", "gate": "feedback_governors", "materials": {"Gear Sets": 1.0, "Shaft Bearings": 1.0, "Steel": 1.0}, "days": 5.0, "tooling": {"Steel": 4.0, "Optical Lenses": 1.0}},
	"governed_generators":{"name": "Governed generator assemblies", "output": "Electrical Generators", "gate": "electrical_generators", "materials": {"Mechanical Governors": 1.0, "Crank Assemblies": 1.0, "Flywheels": 1.0, "Copper Wire": 5.0, "Insulated Cable": 2.0, "Steel": 2.0}, "days": 12.0, "tooling": {"Steel": 6.0, "Timber": 8.0}},

	"purified_brine":{"name": "Purified brine", "output": "Purified Brine", "gate": "brine_purification", "materials": {"Salt": 1.0, "Freshwater": 3.0}, "days": 3.0, "tooling": {"Glass": 2.0, "Clay": 4.0}},
	"chloralkali_batch":{"name": "Chlor-alkali batches", "output": "Chlorine", "co_products": {"Caustic Soda": 1.0, "Hydrogen": 1.0}, "gate": "chloralkali_cells", "materials": {"Purified Brine": 1.0, "Freshwater": 1.0, "Graphite": 0.02}, "days": 5.0, "power": 4.0, "daily_power": 2.0, "tooling": {"Pressure Vessels": 3.0, "Glass": 4.0, "Insulated Cable": 4.0}},
	"hydrogen_chloride":{"name": "Hydrogen chloride", "output": "Hydrogen Chloride", "gate": "hydrogen_chloride_synthesis", "materials": {"Chlorine": 1.0, "Hydrogen": 1.0}, "days": 3.0, "tooling": {"Pressure Vessels": 2.0, "Glass": 3.0}},
	"reagent_refined_silicon":{"name": "Silicon from prepared reagents", "output": "Purified Silicon", "gate": "chlorosilane_purification", "materials": {"Metallurgical Silicon": 1.0, "Hydrogen Chloride": 0.5, "Hydrogen": 0.25, "Freshwater": 1.0}, "days": 6.0, "power": 3.0, "daily_power": 1.5, "tooling": {"Pressure Vessels": 3.0, "Glass": 3.0, "Steel": 5.0}},

	"silicon_feedstock":{"name": "Metallurgical silicon", "output": "Metallurgical Silicon", "gate": "silicon_smelting", "materials": {"Fine Sand": 3.0, "Coal": 2.0, "Graphite": 0.1}, "days": 6.0, "power": 6.0, "daily_power": 2.0, "tooling": {"Steel": 8.0, "Refractory Clay": 10.0, "Insulated Cable": 4.0}},
	"purified_silicon":{"name": "Purified silicon", "output": "Purified Silicon", "gate": "chlorosilane_purification", "materials": {"Metallurgical Silicon": 1.0, "Salt": 0.5, "Freshwater": 2.0}, "days": 8.0, "power": 4.0, "daily_power": 1.5, "tooling": {"Pressure Vessels": 3.0, "Glass": 3.0, "Steel": 5.0}},
	"silicon_boules":{"name": "Silicon crystal boules", "output": "Silicon Boules", "gate": "single_crystal_growth", "materials": {"Purified Silicon": 1.0, "Graphite": 0.1}, "days": 8.0, "power": 4.0, "daily_power": 1.5, "tooling": {"Pressure Vessels": 1.0, "Glass": 2.0, "Steel": 4.0}},
	"silicon_wafers":{"name": "Sawn silicon wafers", "output": "Silicon Wafers", "gate": "wafer_sawing", "materials": {"Silicon Boules": 1.0, "Fine Sand": 0.2, "Freshwater": 1.0}, "days": 4.0, "tooling": {"Copper Wire": 2.0, "Steel": 3.0, "Optical Lenses": 1.0}},
	"solar_cells":{"name": "Photovoltaic cells", "output": "Solar Cells", "gate": "solar_cell_fabrication", "materials": {"Silicon Wafers": 1.0, "Refined Copper": 0.2, "Phosphate Rock": 0.02, "Freshwater": 2.0}, "days": 6.0, "power": 2.0, "daily_power": 1.0, "tooling": {"Glass": 3.0, "Optical Lenses": 2.0, "Pressure Vessels": 1.0}},
	"solar_modules":{"name": "Photovoltaic modules", "output": "Photovoltaic Modules", "gate": "module_encapsulation", "materials": {"Solar Cells": 2.0, "Glass": 2.0, "Insulated Cable": 1.0, "Steel": 1.0}, "days": 6.0, "tooling": {"Steel": 3.0, "Timber": 3.0}},
	"electric_arc_steel":{"name":"Electric-arc steel","output":"Steel","gate":"electric_arc_furnaces","materials":{"Wrought Iron":2.0,"Limestone":.2,"Graphite":.1},"days":4.0,"power":6.0,"daily_power":2.0,"tooling":{"Steel":8.0,"Insulated Cable":4.0,"Refractory Clay":10.0}},
	"glass_batch":{"name":"Glass batches","output":"Glass","gate":"glassmaking","materials":{"Fine Sand":2.0,"Limestone":.3,"Timber":3.0},"days":3.0,"tooling":{"Stone":12.0,"Clay":8.0}},
	"refined_copper":{"name":"Refined copper","output":"Refined Copper","gate":"copper_smelting","materials":{"Copper Ore":2.0,"Timber":2.0},"days":3.0,"tooling":{"Stone":12.0,"Clay":8.0}},
	"wrought_iron":{"name":"Wrought iron","output":"Wrought Iron","gate":"bloomery_smelting","materials":{"Iron Ore":3.0,"Timber":4.0},"days":5.0,"tooling":{"Stone":18.0,"Clay":12.0}},
	"steel_stock":{"name":"Refined steel","output":"Steel","gate":"steel_refining","materials":{"Wrought Iron":2.0,"Coal":1.0,"Limestone":.2},"days":6.0,"tooling":{"Stone":24.0,"Clay":16.0}},
	"copper_wire":{"name":"Drawn copper wire","output":"Copper Wire","gate":"wire_drawing","materials":{"Refined Copper":1.0},"days":2.0,"tooling":{"Wrought Iron":3.0,"Timber":5.0}},
	"insulated_cable":{"name":"Insulated cable","output":"Insulated Cable","gate":"cable_insulation","materials":{"Copper Wire":1.0,"Fiber Plants":1.0,"Bitumen":.2},"days":2.0,"tooling":{"Timber":8.0,"Clay":2.0}},
	"optical_lens":{"name":"Ground optical lenses","output":"Optical Lenses","gate":"optical_lenses","materials":{"Glass":1.0,"Fine Sand":.3},"days":4.0,"tooling":{"Timber":5.0,"Stone":5.0}},
	"pressure_vessel":{"name":"Pressure vessels","output":"Pressure Vessels","gate":"pressure_vessels","materials":{"Wrought Iron":3.0,"Coal":1.0},"days":10.0,"tooling":{"Wrought Iron":5.0,"Stone":10.0}},
	"electrical_generator":{"name":"Electrical generators","output":"Electrical Generators","gate":"electrical_generators","materials":{"Refined Copper":5.0,"Wrought Iron":8.0,"Insulated Cable":2.0},"days":20.0,"tooling":{"Wrought Iron":8.0,"Timber":10.0}},
	"electric_motor":{"name":"Electric motors","output":"Electric Motors","gate":"electric_motors","materials":{"Wrought Iron":4.0,"Copper Wire":3.0,"Insulated Cable":2.0},"days":12.0,"tooling":{"Wrought Iron":6.0,"Timber":8.0}}
}
static func product(item:String)->Dictionary:return PRODUCTS.get(item,{})
static func entries()->Array[Dictionary]:
	return [
		{"id":"electric_arc_furnaces","name":"Electric Arc Furnaces","direction":"Materials","day":82000,"chance":.002,"requires":["steel_refining","electrical_generators","electrical_measurement"],"signals":["crafting","materials","research"],"observation":"An arc between carbon electrodes supplies controllable heat inside a refractory-lined steelmaking vessel.","effects":{},"production_contract":"An alternative steel workshop consumes iron, flux, graphite electrodes and shared daily electricity. Fuel-fired refining remains available without electricity.","production_items":["electric_arc_steel"]},
		{"id":"mechanical_refrigeration","name":"Mechanical Refrigeration","direction":"Infrastructure","day":76000,"chance":.002,"requires":["heat_engine_cycles","pressure_vessels","electric_motors"],"signals":["food","crafting","research"],"observation":"Powered compression and expansion move heat from a storage enclosure into its surroundings.","effects":{},"production_contract":"Enables commissioning of electric cold stores; capacity exists only while machinery, operators and power actually operate.","operating_plants":["cold_store"]},
		{"id":"steel_refining","name":"Steel Refining","direction":"Materials","day":54000,"chance":.002,"requires":["bloomery_smelting","coke_firing","precision_thermometry"],"signals":["crafting","materials","research"],"observation":"Controlled refining compares carbon content and the behavior of iron under working loads.","effects":{},"production_contract":"Enables a finite workshop line converting wrought iron, coal and flux into steel batches.","production_items":["steel_stock"]},
		{"id":"wire_drawing","name":"Wire Drawing","direction":"Materials","day":26000,"chance":.003,"requires":["copper_casting","workshop_standards"],"signals":["crafting","materials"],"observation":"Successive dies reduce drawn metal to repeatable wire sections.","effects":{},"production_contract":"Converts physically refined copper to wire using workshop labor and iron tooling.","production_items":["copper_wire"]},
		{"id":"cable_insulation","name":"Cable Insulation","direction":"Materials","day":44000,"chance":.002,"requires":["wire_drawing","bitumen_sealing","electrical_measurement"],"signals":["crafting","research"],"observation":"Wrapped conductors and insulating compounds are tested against leakage and contact faults.","effects":{},"production_contract":"Consumes wire, fibers and bitumen to manufacture insulated cable for motors and generators.","production_items":["insulated_cable"]}
	]
