extends RefCounted
const UNITS:Dictionary={
	"war_canoe": {
		"label": "War Canoes",
		"domain": "navy",
		"gate": "river_craft",
		"lineage": "",
		"equipment": "war_canoe_equipment",
		"crew": 4,
		"range_km": 150,
		"speed_km_day": 20,
		"fuel_per_day": 0,
		"mission": "patrol",
		"attack": 0.5,
		"defense": 0.4,
		"detection": 0.8,
		"training_days": 60,
		"materials": {
			"Timber": 40.0,
			"Fiber Plants": 10.0
		},
		"work_days": 8,
		"carrier_capacity": 0,
		"purpose": "Patrol"
	},
	"galley": {
		"label": "Ram Galleys",
		"domain": "navy",
		"gate": "galley_navigation",
		"lineage": "war_canoe",
		"equipment": "galley_equipment",
		"crew": 80,
		"range_km": 500,
		"speed_km_day": 100,
		"fuel_per_day": 0,
		"mission": "strike_force",
		"attack": 2,
		"defense": 1,
		"detection": 1,
		"training_days": 60,
		"materials": {
			"Timber": 40.0,
			"Fiber Plants": 10.0
		},
		"work_days": 48.0,
		"carrier_capacity": 0,
		"purpose": "Strike force"
	},
	"heavy_galley": {
		"label": "Heavy Boarding Galleys",
		"domain": "navy",
		"gate": "naval_arsenals",
		"lineage": "galley",
		"equipment": "heavy_galley_equipment",
		"crew": 140,
		"range_km": 650,
		"speed_km_day": 160,
		"fuel_per_day": 0,
		"mission": "strike_force",
		"attack": 3,
		"defense": 2,
		"detection": 0.7,
		"training_days": 60,
		"materials": {
			"Timber": 40.0,
			"Fiber Plants": 10.0
		},
		"work_days": 84.0,
		"carrier_capacity": 0,
		"purpose": "Strike force"
	},
	"sailing_warship": {
		"label": "Sailing Warships",
		"domain": "navy",
		"gate": "ocean_sailing",
		"lineage": "galley",
		"equipment": "sailing_warship_equipment",
		"crew": 80,
		"range_km": 2000,
		"speed_km_day": 150,
		"fuel_per_day": 0,
		"mission": "patrol",
		"attack": 2,
		"defense": 1.5,
		"detection": 1.4,
		"training_days": 60,
		"materials": {
			"Timber": 40.0,
			"Fiber Plants": 10.0
		},
		"work_days": 48.0,
		"carrier_capacity": 0,
		"purpose": "Patrol"
	},
	"sailing_frigate": {
		"label": "Sailing Frigates",
		"domain": "navy",
		"gate": "naval_gunnery",
		"lineage": "sailing_warship",
		"equipment": "sailing_frigate_equipment",
		"crew": 180,
		"range_km": 3500,
		"speed_km_day": 220,
		"fuel_per_day": 0,
		"mission": "convoy_escort",
		"attack": 3,
		"defense": 2,
		"detection": 2,
		"training_days": 60,
		"materials": {
			"Timber": 40.0,
			"Fiber Plants": 10.0
		},
		"work_days": 108.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort"
	},
	"ship_of_line": {
		"label": "Ships of the Line",
		"domain": "navy",
		"gate": "naval_gunnery",
		"lineage": "heavy_galley",
		"equipment": "ship_of_line_equipment",
		"crew": 500,
		"range_km": 3000,
		"speed_km_day": 400,
		"fuel_per_day": 0,
		"mission": "strike_force",
		"attack": 7,
		"defense": 5,
		"detection": 0.6,
		"training_days": 60,
		"materials": {
			"Timber": 40.0,
			"Fiber Plants": 10.0
		},
		"work_days": 300.0,
		"carrier_capacity": 0,
		"purpose": "Strike force"
	},
	"steam_corvette": {
		"label": "Steam Corvettes",
		"domain": "navy",
		"gate": "steam_propulsion",
		"lineage": "sailing_frigate",
		"equipment": "steam_corvette_equipment",
		"crew": 100,
		"range_km": 2500,
		"speed_km_day": 250,
		"fuel_per_day": 3,
		"mission": "convoy_escort",
		"attack": 2.5,
		"defense": 2,
		"detection": 2,
		"training_days": 60,
		"materials": {
			"Iron Ore": 33.0,
			"Copper Ore": 6.0,
			"Fiber Plants": 3.0
		},
		"work_days": 60.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort"
	},
	"ironclad": {
		"label": "Ironclads",
		"domain": "navy",
		"gate": "armored_hulls",
		"lineage": "ship_of_line",
		"equipment": "ironclad_equipment",
		"crew": 250,
		"range_km": 1800,
		"speed_km_day": 300,
		"fuel_per_day": 6,
		"mission": "strike_force",
		"attack": 6,
		"defense": 7,
		"detection": 0.7,
		"training_days": 60,
		"materials": {
			"Iron Ore": 83.0,
			"Copper Ore": 16.0,
			"Fiber Plants": 8.0
		},
		"work_days": 150.0,
		"carrier_capacity": 0,
		"purpose": "Strike force"
	},
	"torpedo_boat": {
		"label": "Torpedo Boats",
		"domain": "navy",
		"gate": "naval_torpedoes",
		"lineage": "steam_corvette",
		"equipment": "torpedo_boat_equipment",
		"crew": 20,
		"range_km": 700,
		"speed_km_day": 600,
		"fuel_per_day": 2,
		"mission": "convoy_raiding",
		"attack": 5,
		"defense": 0.8,
		"detection": 1.8,
		"training_days": 60,
		"materials": {
			"Iron Ore": 6.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 12.0,
		"carrier_capacity": 0,
		"purpose": "Convoy raiding"
	},
	"destroyer": {
		"label": "Destroyers",
		"domain": "navy",
		"gate": "naval_torpedoes",
		"lineage": "torpedo_boat",
		"equipment": "destroyer_equipment",
		"crew": 150,
		"range_km": 3500,
		"speed_km_day": 600,
		"fuel_per_day": 5,
		"mission": "convoy_escort",
		"attack": 4,
		"defense": 2.5,
		"detection": 3,
		"training_days": 60,
		"materials": {
			"Iron Ore": 50.0,
			"Copper Ore": 10.0,
			"Fiber Plants": 5.0
		},
		"work_days": 90.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort"
	},
	"light_cruiser": {
		"label": "Light Cruisers",
		"domain": "navy",
		"gate": "armored_hulls",
		"lineage": "sailing_frigate",
		"equipment": "light_cruiser_equipment",
		"crew": 350,
		"range_km": 5000,
		"speed_km_day": 550,
		"fuel_per_day": 7,
		"mission": "patrol",
		"attack": 5,
		"defense": 4,
		"detection": 3,
		"training_days": 60,
		"materials": {
			"Iron Ore": 116.0,
			"Copper Ore": 23.0,
			"Fiber Plants": 11.0
		},
		"work_days": 210.0,
		"carrier_capacity": 0,
		"purpose": "Patrol"
	},
	"heavy_cruiser": {
		"label": "Heavy Cruisers",
		"domain": "navy",
		"gate": "naval_fire_control",
		"lineage": "light_cruiser",
		"equipment": "heavy_cruiser_equipment",
		"crew": 600,
		"range_km": 6000,
		"speed_km_day": 500,
		"fuel_per_day": 10,
		"mission": "strike_force",
		"attack": 8,
		"defense": 6,
		"detection": 2,
		"training_days": 60,
		"materials": {
			"Iron Ore": 200.0,
			"Copper Ore": 40.0,
			"Fiber Plants": 20.0
		},
		"work_days": 360.0,
		"carrier_capacity": 0,
		"purpose": "Strike force"
	},
	"battleship": {
		"label": "Battleships",
		"domain": "navy",
		"gate": "naval_fire_control",
		"lineage": "ironclad",
		"equipment": "battleship_equipment",
		"crew": 1100,
		"range_km": 6500,
		"speed_km_day": 420,
		"fuel_per_day": 16,
		"mission": "strike_force",
		"attack": 14,
		"defense": 12,
		"detection": 1,
		"training_days": 60,
		"materials": {
			"Iron Ore": 366.0,
			"Copper Ore": 73.0,
			"Fiber Plants": 36.0
		},
		"work_days": 660.0,
		"carrier_capacity": 0,
		"purpose": "Strike force"
	},
	"submarine": {
		"label": "Submarines",
		"domain": "navy",
		"gate": "submersible_hulls",
		"lineage": "torpedo_boat",
		"equipment": "submarine_equipment",
		"crew": 45,
		"range_km": 5000,
		"speed_km_day": 350,
		"fuel_per_day": 3,
		"mission": "convoy_raiding",
		"attack": 7,
		"defense": 1,
		"detection": 2,
		"training_days": 60,
		"materials": {
			"Iron Ore": 15.0,
			"Copper Ore": 3.0,
			"Fiber Plants": 1.0
		},
		"work_days": 27.0,
		"carrier_capacity": 0,
		"purpose": "Convoy raiding"
	},
	"aircraft_carrier": {
		"label": "Aircraft Carriers",
		"domain": "navy",
		"gate": "carrier_aviation",
		"lineage": "heavy_cruiser",
		"equipment": "aircraft_carrier_equipment",
		"crew": 900,
		"range_km": 6500,
		"speed_km_day": 500,
		"fuel_per_day": 14,
		"mission": "strike_force",
		"attack": 2,
		"defense": 5,
		"detection": 3,
		"training_days": 60,
		"materials": {
			"Iron Ore": 300.0,
			"Copper Ore": 60.0,
			"Fiber Plants": 30.0
		},
		"work_days": 540.0,
		"carrier_capacity": 60,
		"purpose": "Strike force"
	},
	"amphibious_ship": {
		"label": "Amphibious Assault Ships",
		"domain": "navy",
		"gate": "amphibious_operations",
		"lineage": "sailing_warship",
		"equipment": "amphibious_ship_equipment",
		"crew": 250,
		"range_km": 4500,
		"speed_km_day": 420,
		"fuel_per_day": 9,
		"mission": "invasion_support",
		"attack": 2,
		"defense": 3,
		"detection": 1.5,
		"training_days": 60,
		"materials": {
			"Iron Ore": 83.0,
			"Copper Ore": 16.0,
			"Fiber Plants": 8.0
		},
		"work_days": 150.0,
		"carrier_capacity": 0,
		"purpose": "Invasion support"
	},
	"missile_patrol": {
		"label": "Missile Patrol Boats",
		"domain": "navy",
		"gate": "guided_weapons",
		"lineage": "torpedo_boat",
		"equipment": "missile_patrol_equipment",
		"crew": 25,
		"range_km": 1400,
		"speed_km_day": 650,
		"fuel_per_day": 3,
		"mission": "strike_force",
		"attack": 9,
		"defense": 1,
		"detection": 2.5,
		"training_days": 60,
		"materials": {
			"Iron Ore": 8.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 15.0,
		"carrier_capacity": 0,
		"purpose": "Strike force"
	},
	"missile_destroyer": {
		"label": "Missile Destroyers",
		"domain": "navy",
		"gate": "naval_missiles",
		"lineage": "destroyer",
		"equipment": "missile_destroyer_equipment",
		"crew": 220,
		"range_km": 6500,
		"speed_km_day": 580,
		"fuel_per_day": 8,
		"mission": "convoy_escort",
		"attack": 12,
		"defense": 6,
		"detection": 5,
		"training_days": 60,
		"materials": {
			"Iron Ore": 73.0,
			"Copper Ore": 14.0,
			"Fiber Plants": 7.0
		},
		"work_days": 132.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort"
	},
	"nuclear_submarine": {
		"label": "Nuclear Submarines",
		"domain": "navy",
		"gate": "nuclear_propulsion",
		"lineage": "submarine",
		"equipment": "nuclear_submarine_equipment",
		"crew": 120,
		"range_km": 16000,
		"speed_km_day": 600,
		"fuel_per_day": 0,
		"mission": "convoy_raiding",
		"attack": 14,
		"defense": 4,
		"detection": 5,
		"training_days": 60,
		"materials": {
			"Iron Ore": 40.0,
			"Copper Ore": 8.0,
			"Fiber Plants": 4.0
		},
		"work_days": 72.0,
		"carrier_capacity": 0,
		"purpose": "Convoy raiding"
	},
	"fleet_support": {
		"label": "Fleet Support Ships",
		"domain": "navy",
		"gate": "naval_logistics",
		"lineage": "steam_corvette",
		"equipment": "fleet_support_equipment",
		"crew": 130,
		"range_km": 10000,
		"speed_km_day": 420,
		"fuel_per_day": 6,
		"mission": "convoy_escort",
		"attack": 0.5,
		"defense": 2,
		"detection": 1,
		"training_days": 60,
		"materials": {
			"Iron Ore": 43.0,
			"Copper Ore": 8.0,
			"Fiber Plants": 4.0
		},
		"work_days": 78.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort"
	},
	"observation_balloon": {
		"label": "Observation Balloons",
		"domain": "air",
		"gate": "aerostat_observation",
		"lineage": "",
		"equipment": "observation_balloon_equipment",
		"crew": 3,
		"range_km": 100,
		"speed_km_day": 0,
		"fuel_per_day": 0,
		"mission": "reconnaissance",
		"attack": 0,
		"defense": 0.2,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 24,
		"carrier_capacity": 0,
		"purpose": "Reconnaissance"
	},
	"airship": {
		"label": "Patrol Airships",
		"domain": "air",
		"gate": "powered_flight",
		"lineage": "observation_balloon",
		"equipment": "airship_equipment",
		"crew": 12,
		"range_km": 1800,
		"speed_km_day": 200,
		"fuel_per_day": 2,
		"mission": "reconnaissance",
		"attack": 1,
		"defense": 0.6,
		"detection": 3,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 60,
		"carrier_capacity": 0,
		"purpose": "Reconnaissance"
	},
	"recon_plane": {
		"label": "Reconnaissance Aircraft",
		"domain": "air",
		"gate": "powered_flight",
		"lineage": "observation_balloon",
		"equipment": "recon_plane_equipment",
		"crew": 2,
		"range_km": 800,
		"speed_km_day": 500,
		"fuel_per_day": 1,
		"mission": "reconnaissance",
		"attack": 0.3,
		"defense": 0.5,
		"detection": 4,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 20,
		"carrier_capacity": 0,
		"purpose": "Reconnaissance"
	},
	"fighter": {
		"label": "Fighters",
		"domain": "air",
		"gate": "fighter_tactics",
		"lineage": "recon_plane",
		"equipment": "fighter_equipment",
		"crew": 1,
		"range_km": 650,
		"speed_km_day": 800,
		"fuel_per_day": 1,
		"mission": "air_superiority",
		"attack": 3,
		"defense": 2,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 16,
		"carrier_capacity": 0,
		"purpose": "Air superiority"
	},
	"heavy_fighter": {
		"label": "Heavy Fighters",
		"domain": "air",
		"gate": "advanced_airframes",
		"lineage": "fighter",
		"equipment": "heavy_fighter_equipment",
		"crew": 2,
		"range_km": 1500,
		"speed_km_day": 750,
		"fuel_per_day": 2,
		"mission": "interception",
		"attack": 4,
		"defense": 2.5,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 20,
		"carrier_capacity": 0,
		"purpose": "Interception"
	},
	"close_air_support": {
		"label": "Ground-Attack Aircraft",
		"domain": "air",
		"gate": "aerial_bombardment",
		"lineage": "fighter",
		"equipment": "close_air_support_equipment",
		"crew": 1,
		"range_km": 550,
		"speed_km_day": 650,
		"fuel_per_day": 2,
		"mission": "close_air_support",
		"attack": 4,
		"defense": 1.5,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 16,
		"carrier_capacity": 0,
		"purpose": "Close air support"
	},
	"tactical_bomber": {
		"label": "Tactical Bombers",
		"domain": "air",
		"gate": "aerial_bombardment",
		"lineage": "airship",
		"equipment": "tactical_bomber_equipment",
		"crew": 4,
		"range_km": 1800,
		"speed_km_day": 650,
		"fuel_per_day": 4,
		"mission": "logistics_strike",
		"attack": 5,
		"defense": 1.7,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 28,
		"carrier_capacity": 0,
		"purpose": "Logistics strike"
	},
	"strategic_bomber": {
		"label": "Strategic Bombers",
		"domain": "air",
		"gate": "advanced_airframes",
		"lineage": "tactical_bomber",
		"equipment": "strategic_bomber_equipment",
		"crew": 7,
		"range_km": 3500,
		"speed_km_day": 650,
		"fuel_per_day": 7,
		"mission": "strategic_bombing",
		"attack": 9,
		"defense": 3,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 40,
		"carrier_capacity": 0,
		"purpose": "Strategic bombing"
	},
	"naval_bomber": {
		"label": "Naval Bombers",
		"domain": "air",
		"gate": "naval_aviation",
		"lineage": "tactical_bomber",
		"equipment": "naval_bomber_equipment",
		"crew": 3,
		"range_km": 1600,
		"speed_km_day": 600,
		"fuel_per_day": 3,
		"mission": "naval_strike",
		"attack": 7,
		"defense": 1.3,
		"detection": 3,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 24,
		"carrier_capacity": 0,
		"purpose": "Naval strike"
	},
	"transport_aircraft": {
		"label": "Transport Aircraft",
		"domain": "air",
		"gate": "airborne_operations",
		"lineage": "tactical_bomber",
		"equipment": "transport_aircraft_equipment",
		"crew": 4,
		"range_km": 2200,
		"speed_km_day": 600,
		"fuel_per_day": 4,
		"mission": "air_supply",
		"attack": 0,
		"defense": 1,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 28,
		"carrier_capacity": 0,
		"purpose": "Air supply"
	},
	"jet_fighter": {
		"label": "Jet Fighters",
		"domain": "air",
		"gate": "jet_propulsion",
		"lineage": "fighter",
		"equipment": "jet_fighter_equipment",
		"crew": 1,
		"range_km": 1500,
		"speed_km_day": 1800,
		"fuel_per_day": 3,
		"mission": "air_superiority",
		"attack": 7,
		"defense": 5,
		"detection": 3,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 16,
		"carrier_capacity": 0,
		"purpose": "Air superiority"
	},
	"jet_bomber": {
		"label": "Jet Bombers",
		"domain": "air",
		"gate": "jet_propulsion",
		"lineage": "strategic_bomber",
		"equipment": "jet_bomber_equipment",
		"crew": 3,
		"range_km": 4500,
		"speed_km_day": 1200,
		"fuel_per_day": 8,
		"mission": "strategic_bombing",
		"attack": 12,
		"defense": 4,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 24,
		"carrier_capacity": 0,
		"purpose": "Strategic bombing"
	},
	"transport_helicopter": {
		"label": "Transport Helicopters",
		"domain": "air",
		"gate": "rotary_wing",
		"lineage": "transport_aircraft",
		"equipment": "transport_helicopter_equipment",
		"crew": 2,
		"range_km": 450,
		"speed_km_day": 300,
		"fuel_per_day": 2,
		"mission": "air_supply",
		"attack": 0,
		"defense": 1,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 20,
		"carrier_capacity": 0,
		"purpose": "Air supply"
	},
	"attack_helicopter": {
		"label": "Attack Helicopters",
		"domain": "air",
		"gate": "guided_weapons",
		"lineage": "transport_helicopter",
		"equipment": "attack_helicopter_equipment",
		"crew": 2,
		"range_km": 400,
		"speed_km_day": 350,
		"fuel_per_day": 3,
		"mission": "close_air_support",
		"attack": 8,
		"defense": 2,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 20,
		"carrier_capacity": 0,
		"purpose": "Close air support"
	},
	"recon_drone": {
		"label": "Reconnaissance Drones",
		"domain": "air",
		"gate": "remote_aircraft",
		"lineage": "recon_plane",
		"equipment": "recon_drone_equipment",
		"crew": 2,
		"range_km": 1800,
		"speed_km_day": 400,
		"fuel_per_day": 1,
		"mission": "reconnaissance",
		"attack": 0,
		"defense": 1,
		"detection": 8,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 20,
		"carrier_capacity": 0,
		"purpose": "Reconnaissance"
	},
	"strike_drone": {
		"label": "Strike Drones",
		"domain": "air",
		"gate": "remote_aircraft",
		"lineage": "close_air_support",
		"equipment": "strike_drone_equipment",
		"crew": 2,
		"range_km": 1400,
		"speed_km_day": 450,
		"fuel_per_day": 2,
		"mission": "close_air_support",
		"attack": 7,
		"defense": 2,
		"detection": 5,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.0,
			"Copper Ore": 1.0,
			"Fiber Plants": 1.0
		},
		"work_days": 20,
		"carrier_capacity": 0,
		"purpose": "Close air support"
	}
}

static func by_equipment(item:String)->Dictionary:
	for unit:Dictionary in UNITS.values():
		if String(unit.equipment)==item:return unit
	return {}
