extends RefCounted
const UNITS:Dictionary={
	"war_canoe": {
		"label": "War Canoes",
		"domain": "navy",
		"gate": "river_craft",
		"lineage": "",
		"equipment": "war_canoe_equipment",
		"crew": 4,
		"range_km": 150,
		"speed_km_day": 20,
		"fuel_per_day": 0,
		"mission": "patrol",
		"attack": 0.5,
		"defense": 0.4,
		"detection": 0.8,
		"training_days": 60,
		"materials": {
			"Timber": 40,
			"Fiber Plants": 10
		},
		"work_days": 8,
		"carrier_capacity": 0,
		"purpose": "Patrol",
		"carrier_capable": false,
		"cargo_capacity": 8
	},
	"galley": {
		"label": "Ram Galleys",
		"domain": "navy",
		"gate": "galley_navigation",
		"lineage": "war_canoe",
		"equipment": "galley_equipment",
		"crew": 80,
		"range_km": 500,
		"speed_km_day": 100,
		"fuel_per_day": 0,
		"mission": "strike_force",
		"attack": 2,
		"defense": 1,
		"detection": 1,
		"training_days": 60,
		"materials": {
			"Timber": 800.0,
			"Fiber Plants": 200.0
		},
		"work_days": 48.0,
		"carrier_capacity": 0,
		"purpose": "Strike force",
		"carrier_capable": false,
		"cargo_capacity": 30
	},
	"heavy_galley": {
		"label": "Heavy Boarding Galleys",
		"domain": "navy",
		"gate": "naval_arsenals",
		"lineage": "galley",
		"equipment": "heavy_galley_equipment",
		"crew": 140,
		"range_km": 650,
		"speed_km_day": 160,
		"fuel_per_day": 0,
		"mission": "strike_force",
		"attack": 3,
		"defense": 2,
		"detection": 0.7,
		"training_days": 60,
		"materials": {
			"Timber": 1400.0,
			"Fiber Plants": 350.0
		},
		"work_days": 84.0,
		"carrier_capacity": 0,
		"purpose": "Strike force",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"sailing_warship": {
		"label": "Sailing Warships",
		"domain": "navy",
		"gate": "ocean_sailing",
		"lineage": "galley",
		"equipment": "sailing_warship_equipment",
		"crew": 80,
		"range_km": 2000,
		"speed_km_day": 150,
		"fuel_per_day": 0,
		"mission": "patrol",
		"attack": 2,
		"defense": 1.5,
		"detection": 1.4,
		"training_days": 60,
		"materials": {"Hull Sections": 16.0, "Sail Sets": 4.0, "Rigging Sets": 4.0, "Ship Masts": 4.0},
		"tooling": {"Launch Cradles": 1.0},
		"work_days": 48.0,
		"carrier_capacity": 0,
		"purpose": "Patrol",
		"carrier_capable": false,
		"cargo_capacity": 60
	},
	"sailing_frigate": {
		"label": "Sailing Frigates",
		"domain": "navy",
		"gate": "naval_gunnery",
		"lineage": "sailing_warship",
		"equipment": "sailing_frigate_equipment",
		"crew": 180,
		"range_km": 3500,
		"speed_km_day": 220,
		"fuel_per_day": 0,
		"mission": "convoy_escort",
		"attack": 3,
		"defense": 2,
		"detection": 2,
		"training_days": 60,
		"materials": {"Heavy Hull Sections": 36.0, "Sail Sets": 9.0, "Rigging Sets": 9.0, "Ship Masts": 9.0},
		"tooling": {"Launch Cradles": 1.0},
		"work_days": 108.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"ship_of_line": {
		"label": "Ships of the Line",
		"domain": "navy",
		"gate": "naval_gunnery",
		"lineage": "heavy_galley",
		"equipment": "ship_of_line_equipment",
		"crew": 500,
		"range_km": 3000,
		"speed_km_day": 400,
		"fuel_per_day": 0,
		"mission": "strike_force",
		"attack": 7,
		"defense": 5,
		"detection": 0.6,
		"training_days": 60,
		"materials": {"Heavy Hull Sections": 100.0, "Sail Sets": 25.0, "Rigging Sets": 25.0, "Ship Masts": 25.0},
		"tooling": {"Launch Cradles": 1.0},
		"work_days": 300.0,
		"carrier_capacity": 0,
		"purpose": "Strike force",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"steam_corvette": {
		"label": "Steam Corvettes",
		"domain": "navy",
		"gate": "steam_propulsion",
		"lineage": "sailing_frigate",
		"equipment": "steam_corvette_equipment",
		"crew": 100,
		"range_km": 2500,
		"speed_km_day": 250,
		"fuel_per_day": 3,
		"mission": "convoy_escort",
		"attack": 2.5,
		"defense": 2,
		"detection": 2,
		"training_days": 60,
		"materials": {
			"Iron Ore": 200,
			"Copper Ore": 20.0,
			"Graphite": 5.0
		},
		"work_days": 60.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"ironclad": {
		"label": "Ironclads",
		"domain": "navy",
		"gate": "armored_hulls",
		"lineage": "ship_of_line",
		"equipment": "ironclad_equipment",
		"crew": 250,
		"range_km": 1800,
		"speed_km_day": 300,
		"fuel_per_day": 6,
		"mission": "strike_force",
		"attack": 6,
		"defense": 7,
		"detection": 0.7,
		"training_days": 60,
		"materials": {
			"Iron Ore": 500,
			"Copper Ore": 50.0,
			"Graphite": 12.5
		},
		"work_days": 150.0,
		"carrier_capacity": 0,
		"purpose": "Strike force",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"torpedo_boat": {
		"label": "Torpedo Boats",
		"domain": "navy",
		"gate": "naval_torpedoes",
		"lineage": "steam_corvette",
		"equipment": "torpedo_boat_equipment",
		"crew": 20,
		"range_km": 700,
		"speed_km_day": 600,
		"fuel_per_day": 2,
		"mission": "convoy_raiding",
		"attack": 5,
		"defense": 0.8,
		"detection": 1.8,
		"training_days": 60,
		"materials": {
			"Iron Ore": 40,
			"Copper Ore": 4,
			"Graphite": 1
		},
		"work_days": 12.0,
		"carrier_capacity": 0,
		"purpose": "Convoy raiding",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"destroyer": {
		"label": "Destroyers",
		"domain": "navy",
		"gate": "naval_torpedoes",
		"lineage": "torpedo_boat",
		"equipment": "destroyer_equipment",
		"crew": 150,
		"range_km": 3500,
		"speed_km_day": 600,
		"fuel_per_day": 5,
		"mission": "convoy_escort",
		"attack": 4,
		"defense": 2.5,
		"detection": 3,
		"training_days": 60,
		"materials": {
			"Iron Ore": 300,
			"Copper Ore": 30.0,
			"Graphite": 7.5
		},
		"work_days": 90.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"light_cruiser": {
		"label": "Light Cruisers",
		"domain": "navy",
		"gate": "armored_hulls",
		"lineage": "sailing_frigate",
		"equipment": "light_cruiser_equipment",
		"crew": 350,
		"range_km": 5000,
		"speed_km_day": 550,
		"fuel_per_day": 7,
		"mission": "patrol",
		"attack": 5,
		"defense": 4,
		"detection": 3,
		"training_days": 60,
		"materials": {
			"Iron Ore": 700,
			"Copper Ore": 70.0,
			"Graphite": 17.5
		},
		"work_days": 210.0,
		"carrier_capacity": 0,
		"purpose": "Patrol",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"heavy_cruiser": {
		"label": "Heavy Cruisers",
		"domain": "navy",
		"gate": "naval_fire_control",
		"lineage": "light_cruiser",
		"equipment": "heavy_cruiser_equipment",
		"crew": 600,
		"range_km": 6000,
		"speed_km_day": 500,
		"fuel_per_day": 10,
		"mission": "strike_force",
		"attack": 8,
		"defense": 6,
		"detection": 2,
		"training_days": 60,
		"materials": {
			"Iron Ore": 1200,
			"Copper Ore": 120.0,
			"Graphite": 30.0
		},
		"work_days": 360.0,
		"carrier_capacity": 0,
		"purpose": "Strike force",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"battleship": {
		"label": "Battleships",
		"domain": "navy",
		"gate": "naval_fire_control",
		"lineage": "ironclad",
		"equipment": "battleship_equipment",
		"crew": 1100,
		"range_km": 6500,
		"speed_km_day": 420,
		"fuel_per_day": 16,
		"mission": "strike_force",
		"attack": 14,
		"defense": 12,
		"detection": 1,
		"training_days": 60,
		"materials": {
			"Iron Ore": 2200,
			"Copper Ore": 220.0,
			"Graphite": 55.0
		},
		"work_days": 660.0,
		"carrier_capacity": 0,
		"purpose": "Strike force",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"submarine": {
		"label": "Submarines",
		"domain": "navy",
		"gate": "submersible_hulls",
		"lineage": "torpedo_boat",
		"equipment": "submarine_equipment",
		"crew": 45,
		"range_km": 5000,
		"speed_km_day": 350,
		"fuel_per_day": 3,
		"mission": "convoy_raiding",
		"attack": 7,
		"defense": 1,
		"detection": 2,
		"training_days": 60,
		"materials": {
			"Iron Ore": 90,
			"Copper Ore": 9.0,
			"Graphite": 2.25
		},
		"work_days": 27.0,
		"carrier_capacity": 0,
		"purpose": "Convoy raiding",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"aircraft_carrier": {
		"label": "Aircraft Carriers",
		"domain": "navy",
		"gate": "carrier_aviation",
		"lineage": "heavy_cruiser",
		"equipment": "aircraft_carrier_equipment",
		"crew": 900,
		"range_km": 6500,
		"speed_km_day": 500,
		"fuel_per_day": 14,
		"mission": "strike_force",
		"attack": 2,
		"defense": 5,
		"detection": 3,
		"training_days": 60,
		"materials": {
			"Iron Ore": 1800,
			"Copper Ore": 180.0,
			"Graphite": 45.0
		},
		"work_days": 540.0,
		"carrier_capacity": 60,
		"purpose": "Strike force",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"amphibious_ship": {
		"label": "Amphibious Assault Ships",
		"domain": "navy",
		"gate": "amphibious_operations",
		"lineage": "sailing_warship",
		"equipment": "amphibious_ship_equipment",
		"crew": 250,
		"range_km": 4500,
		"speed_km_day": 420,
		"fuel_per_day": 9,
		"mission": "invasion_support",
		"attack": 2,
		"defense": 3,
		"detection": 1.5,
		"training_days": 60,
		"materials": {
			"Iron Ore": 500,
			"Copper Ore": 50.0,
			"Graphite": 12.5
		},
		"work_days": 150.0,
		"carrier_capacity": 0,
		"purpose": "Invasion support",
		"carrier_capable": false,
		"cargo_capacity": 600
	},
	"missile_patrol": {
		"label": "Missile Patrol Boats",
		"domain": "navy",
		"gate": "guided_weapons",
		"lineage": "torpedo_boat",
		"equipment": "missile_patrol_equipment",
		"crew": 25,
		"range_km": 1400,
		"speed_km_day": 650,
		"fuel_per_day": 3,
		"mission": "strike_force",
		"attack": 9,
		"defense": 1,
		"detection": 2.5,
		"training_days": 60,
		"materials": {
			"Iron Ore": 50,
			"Copper Ore": 5.0,
			"Graphite": 1.25
		},
		"work_days": 15.0,
		"carrier_capacity": 0,
		"purpose": "Strike force",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"missile_destroyer": {
		"label": "Missile Destroyers",
		"domain": "navy",
		"gate": "naval_missiles",
		"lineage": "destroyer",
		"equipment": "missile_destroyer_equipment",
		"crew": 220,
		"range_km": 6500,
		"speed_km_day": 580,
		"fuel_per_day": 8,
		"mission": "convoy_escort",
		"attack": 12,
		"defense": 6,
		"detection": 5,
		"training_days": 60,
		"materials": {
			"Iron Ore": 440,
			"Copper Ore": 44.0,
			"Graphite": 11.0
		},
		"work_days": 132.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"nuclear_submarine": {
		"label": "Nuclear Submarines",
		"domain": "navy",
		"gate": "nuclear_propulsion",
		"lineage": "submarine",
		"equipment": "nuclear_submarine_equipment",
		"crew": 120,
		"range_km": 16000,
		"speed_km_day": 600,
		"fuel_per_day": 0,
		"mission": "convoy_raiding",
		"attack": 14,
		"defense": 4,
		"detection": 5,
		"training_days": 60,
		"materials": {
			"Iron Ore": 240,
			"Copper Ore": 24.0,
			"Graphite": 6.0,
			"Uranium Ore": 8.0
		},
		"work_days": 72.0,
		"carrier_capacity": 0,
		"purpose": "Convoy raiding",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"fleet_support": {
		"label": "Fleet Support Ships",
		"domain": "navy",
		"gate": "naval_logistics",
		"lineage": "steam_corvette",
		"equipment": "fleet_support_equipment",
		"crew": 130,
		"range_km": 10000,
		"speed_km_day": 420,
		"fuel_per_day": 6,
		"mission": "convoy_escort",
		"attack": 0.5,
		"defense": 2,
		"detection": 1,
		"training_days": 60,
		"materials": {
			"Iron Ore": 260,
			"Copper Ore": 26.0,
			"Graphite": 6.5
		},
		"work_days": 78.0,
		"carrier_capacity": 0,
		"purpose": "Convoy escort",
		"carrier_capable": false,
		"cargo_capacity": 800
	},
	"observation_balloon": {
		"label": "Observation Balloons",
		"domain": "air",
		"gate": "aerostat_observation",
		"lineage": "",
		"equipment": "observation_balloon_equipment",
		"crew": 3,
		"range_km": 100,
		"speed_km_day": 0,
		"fuel_per_day": 0,
		"mission": "reconnaissance",
		"attack": 0,
		"defense": 0.2,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Fiber Plants": 20.0,
			"Timber": 5.0,
			"Bitumen": 2.0
		},
		"work_days": 24,
		"carrier_capacity": 0,
		"purpose": "Reconnaissance",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"airship": {
		"label": "Patrol Airships",
		"domain": "air",
		"gate": "powered_flight",
		"lineage": "observation_balloon",
		"equipment": "airship_equipment",
		"crew": 12,
		"range_km": 1800,
		"speed_km_day": 200,
		"fuel_per_day": 2,
		"mission": "reconnaissance",
		"attack": 1,
		"defense": 0.6,
		"detection": 3,
		"training_days": 90,
		"materials": {
			"Iron Ore": 24,
			"Copper Ore": 12,
			"Fiber Plants": 18,
			"Graphite": 6
		},
		"work_days": 120,
		"carrier_capacity": 0,
		"purpose": "Reconnaissance",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"recon_plane": {
		"label": "Reconnaissance Aircraft",
		"domain": "air",
		"gate": "powered_flight",
		"lineage": "observation_balloon",
		"equipment": "recon_plane_equipment",
		"crew": 2,
		"range_km": 800,
		"speed_km_day": 500,
		"fuel_per_day": 1,
		"mission": "reconnaissance",
		"attack": 0.3,
		"defense": 0.5,
		"detection": 4,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4,
			"Copper Ore": 2,
			"Fiber Plants": 3,
			"Graphite": 1
		},
		"work_days": 20,
		"carrier_capacity": 0,
		"purpose": "Reconnaissance",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"fighter": {
		"label": "Fighters",
		"domain": "air",
		"gate": "fighter_tactics",
		"lineage": "recon_plane",
		"equipment": "fighter_equipment",
		"crew": 1,
		"range_km": 650,
		"speed_km_day": 800,
		"fuel_per_day": 1,
		"mission": "air_superiority",
		"attack": 3,
		"defense": 2,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4,
			"Copper Ore": 2,
			"Fiber Plants": 3,
			"Graphite": 1
		},
		"work_days": 20,
		"carrier_capacity": 0,
		"purpose": "Air superiority",
		"carrier_capable": true,
		"cargo_capacity": 0
	},
	"heavy_fighter": {
		"label": "Heavy Fighters",
		"domain": "air",
		"gate": "advanced_airframes",
		"lineage": "fighter",
		"equipment": "heavy_fighter_equipment",
		"crew": 2,
		"range_km": 1500,
		"speed_km_day": 750,
		"fuel_per_day": 2,
		"mission": "interception",
		"attack": 4,
		"defense": 2.5,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 8,
			"Copper Ore": 4,
			"Fiber Plants": 6,
			"Graphite": 2
		},
		"work_days": 40,
		"carrier_capacity": 0,
		"purpose": "Interception",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"close_air_support": {
		"label": "Ground-Attack Aircraft",
		"domain": "air",
		"gate": "aerial_bombardment",
		"lineage": "fighter",
		"equipment": "close_air_support_equipment",
		"crew": 1,
		"range_km": 550,
		"speed_km_day": 650,
		"fuel_per_day": 2,
		"mission": "close_air_support",
		"attack": 4,
		"defense": 1.5,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 4.4,
			"Copper Ore": 2.2,
			"Fiber Plants": 3.3000000000000003,
			"Graphite": 1.1
		},
		"work_days": 22.0,
		"carrier_capacity": 0,
		"purpose": "Close air support",
		"carrier_capable": true,
		"cargo_capacity": 0
	},
	"tactical_bomber": {
		"label": "Tactical Bombers",
		"domain": "air",
		"gate": "aerial_bombardment",
		"lineage": "airship",
		"equipment": "tactical_bomber_equipment",
		"crew": 4,
		"range_km": 1800,
		"speed_km_day": 650,
		"fuel_per_day": 4,
		"mission": "logistics_strike",
		"attack": 5,
		"defense": 1.7,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 12,
			"Copper Ore": 6,
			"Fiber Plants": 9,
			"Graphite": 3
		},
		"work_days": 60,
		"carrier_capacity": 0,
		"purpose": "Logistics strike",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"strategic_bomber": {
		"label": "Strategic Bombers",
		"domain": "air",
		"gate": "advanced_airframes",
		"lineage": "tactical_bomber",
		"equipment": "strategic_bomber_equipment",
		"crew": 7,
		"range_km": 3500,
		"speed_km_day": 650,
		"fuel_per_day": 7,
		"mission": "strategic_bombing",
		"attack": 9,
		"defense": 3,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 28,
			"Copper Ore": 14,
			"Fiber Plants": 21,
			"Graphite": 7
		},
		"work_days": 140,
		"carrier_capacity": 0,
		"purpose": "Strategic bombing",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"naval_bomber": {
		"label": "Naval Bombers",
		"domain": "air",
		"gate": "naval_aviation",
		"lineage": "tactical_bomber",
		"equipment": "naval_bomber_equipment",
		"crew": 3,
		"range_km": 1600,
		"speed_km_day": 600,
		"fuel_per_day": 3,
		"mission": "naval_strike",
		"attack": 7,
		"defense": 1.3,
		"detection": 3,
		"training_days": 90,
		"materials": {
			"Iron Ore": 8,
			"Copper Ore": 4,
			"Fiber Plants": 6,
			"Graphite": 2
		},
		"work_days": 40,
		"carrier_capacity": 0,
		"purpose": "Naval strike",
		"carrier_capable": true,
		"cargo_capacity": 0
	},
	"transport_aircraft": {
		"label": "Transport Aircraft",
		"domain": "air",
		"gate": "airborne_operations",
		"lineage": "tactical_bomber",
		"equipment": "transport_aircraft_equipment",
		"crew": 4,
		"range_km": 2200,
		"speed_km_day": 600,
		"fuel_per_day": 4,
		"mission": "air_supply",
		"attack": 0,
		"defense": 1,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 16,
			"Copper Ore": 8,
			"Fiber Plants": 12,
			"Graphite": 4
		},
		"work_days": 80,
		"carrier_capacity": 0,
		"purpose": "Air supply",
		"carrier_capable": false,
		"cargo_capacity": 40
	},
	"jet_fighter": {
		"label": "Jet Fighters",
		"domain": "air",
		"gate": "jet_propulsion",
		"lineage": "fighter",
		"equipment": "jet_fighter_equipment",
		"crew": 1,
		"range_km": 1500,
		"speed_km_day": 1800,
		"fuel_per_day": 3,
		"mission": "air_superiority",
		"attack": 7,
		"defense": 5,
		"detection": 3,
		"training_days": 90,
		"materials": {
			"Iron Ore": 12,
			"Copper Ore": 6,
			"Fiber Plants": 9,
			"Graphite": 3
		},
		"work_days": 60,
		"carrier_capacity": 0,
		"purpose": "Air superiority",
		"carrier_capable": true,
		"cargo_capacity": 0
	},
	"jet_bomber": {
		"label": "Jet Bombers",
		"domain": "air",
		"gate": "jet_propulsion",
		"lineage": "strategic_bomber",
		"equipment": "jet_bomber_equipment",
		"crew": 3,
		"range_km": 4500,
		"speed_km_day": 1200,
		"fuel_per_day": 8,
		"mission": "strategic_bombing",
		"attack": 12,
		"defense": 4,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 36,
			"Copper Ore": 18,
			"Fiber Plants": 27,
			"Graphite": 9
		},
		"work_days": 180,
		"carrier_capacity": 0,
		"purpose": "Strategic bombing",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"transport_helicopter": {
		"label": "Transport Helicopters",
		"domain": "air",
		"gate": "rotary_wing",
		"lineage": "transport_aircraft",
		"equipment": "transport_helicopter_equipment",
		"crew": 2,
		"range_km": 450,
		"speed_km_day": 300,
		"fuel_per_day": 2,
		"mission": "air_supply",
		"attack": 0,
		"defense": 1,
		"detection": 1,
		"training_days": 90,
		"materials": {
			"Iron Ore": 8,
			"Copper Ore": 4,
			"Fiber Plants": 6,
			"Graphite": 2
		},
		"work_days": 40,
		"carrier_capacity": 0,
		"purpose": "Air supply",
		"carrier_capable": false,
		"cargo_capacity": 16
	},
	"attack_helicopter": {
		"label": "Attack Helicopters",
		"domain": "air",
		"gate": "guided_weapons",
		"lineage": "transport_helicopter",
		"equipment": "attack_helicopter_equipment",
		"crew": 2,
		"range_km": 400,
		"speed_km_day": 350,
		"fuel_per_day": 3,
		"mission": "close_air_support",
		"attack": 8,
		"defense": 2,
		"detection": 2,
		"training_days": 90,
		"materials": {
			"Iron Ore": 12,
			"Copper Ore": 6,
			"Fiber Plants": 9,
			"Graphite": 3
		},
		"work_days": 60,
		"carrier_capacity": 0,
		"purpose": "Close air support",
		"carrier_capable": false,
		"cargo_capacity": 0
	},
	"recon_drone": {
		"label": "Reconnaissance Drones",
		"domain": "air",
		"gate": "remote_aircraft",
		"lineage": "recon_plane",
		"equipment": "recon_drone_equipment",
		"crew": 2,
		"range_km": 1800,
		"speed_km_day": 400,
		"fuel_per_day": 1,
		"mission": "reconnaissance",
		"attack": 0,
		"defense": 1,
		"detection": 8,
		"training_days": 90,
		"materials": {
			"Iron Ore": 6.0,
			"Copper Ore": 3.0,
			"Fiber Plants": 4.5,
			"Graphite": 1.5
		},
		"work_days": 30.0,
		"carrier_capacity": 0,
		"purpose": "Reconnaissance",
		"carrier_capable": true,
		"cargo_capacity": 0
	},
	"strike_drone": {
		"label": "Strike Drones",
		"domain": "air",
		"gate": "remote_aircraft",
		"lineage": "close_air_support",
		"equipment": "strike_drone_equipment",
		"crew": 2,
		"range_km": 1400,
		"speed_km_day": 450,
		"fuel_per_day": 2,
		"mission": "close_air_support",
		"attack": 7,
		"defense": 2,
		"detection": 5,
		"training_days": 90,
		"materials": {
			"Iron Ore": 8,
			"Copper Ore": 4,
			"Fiber Plants": 6,
			"Graphite": 2
		},
		"work_days": 40,
		"carrier_capacity": 0,
		"purpose": "Close air support",
		"carrier_capable": true,
		"cargo_capacity": 0
	},
	"convoy_transport": {
		"label": "Convoy Transports",
		"domain": "navy",
		"gate": "ocean_sailing",
		"lineage": "sailing_warship",
		"equipment": "convoy_transport_equipment",
		"crew": 12,
		"range_km": 4000,
		"speed_km_day": 180,
		"fuel_per_day": 0,
		"mission": "transport",
		"attack": 0.1,
		"defense": 0.8,
		"detection": 0.3,
		"training_days": 60,
		"materials": {"Hull Sections": 4.0, "Sail Sets": 1.0, "Rigging Sets": 1.0, "Ship Masts": 1.0},
		"tooling": {"Launch Cradles": 1.0},
		"work_days": 60,
		"carrier_capacity": 0,
		"purpose": "Carry supplies and troops along escorted sea routes.",
		"carrier_capable": false,
		"cargo_capacity": 250
	}
}

# First unit per equipment item, in UNITS order (constant data, built once).
static var _by_equipment:Dictionary={}
static func by_equipment(item:String)->Dictionary:
	if _by_equipment.is_empty():
		for unit:Dictionary in UNITS.values():
			if not _by_equipment.has(String(unit.equipment)):_by_equipment[String(unit.equipment)]=unit
	return _by_equipment.get(item,{})
