extends RefCounted

# This is an invisible possibility space, not a player-facing technology tree.
# Entries become eligible only after people encounter the required materials and
# perform relevant work.  "effects" are small, composable causal modifiers used
# by the resource, food, settlement, health, and state simulations.

static func entries() -> Array[Dictionary]:
	return [
		_entry("stone_sorting","Stone Selection","Materials",20,0.010,[],[_r("Stone","recognized")],["stone","crafting"],"Workers learn which local stones hold an edge, split cleanly, or survive repeated blows.",{"survey_speed":0.03,"tool_quality":0.04}),
		_entry("controlled_flaking","Controlled Flaking","Materials",45,0.008,["stone_sorting"],[_r("Flint","recognized")],["stone","crafting"],"Repeated blows begin producing predictable cutting edges instead of accidental shards.",{"tool_quality":0.07,"extraction_yield":0.03,"hunting_yield":0.03}),
		_entry("hafted_tools","Hafted Tools","Materials",100,0.006,["controlled_flaking","cordage"],[_r("Timber","accessible"),_r("Fiber Plants","accessible")],["timber","fiber","crafting"],"Stone, wood, and binding are combined into tools that transfer force through a handle.",{"tool_quality":0.10,"construction_rate":0.05,"extraction_yield":0.06,"warfare_readiness":0.02}),
		_entry("timber_grading","Timber Grading","Nature",30,0.009,[],[_r("Timber","recognized")],["timber","construction"],"Cutters distinguish woods by strength, flexibility, weight, and resistance to rot.",{"timber_yield":0.05,"storage_loss":-0.02,"construction_rate":0.03}),
		_entry("timber_seasoning","Timber Seasoning","Materials",150,0.006,["timber_grading"],[_r("Timber","developed")],["timber","storage","construction"],"Wood stacked away from soil and rain becomes lighter, straighter, and more durable.",{"timber_yield":0.04,"storage_loss":-0.05,"construction_rate":0.04}),
		_entry("framed_construction","Framed Construction","Infrastructure",500,0.004,["joinery","timber_seasoning"],[_r("Timber","developed")],["timber","construction"],"Load-bearing frames separate a structure's strength from the material filling its walls.",{"housing_output":0.10,"construction_rate":0.08,"disaster_resilience":0.03}),
		_entry("fiber_grading","Fiber Grading","Nature",25,0.009,[],[_r("Fiber Plants","recognized")],["fiber","foraging"],"Gatherers sort stems and bark by length, tensile strength, and behavior when wet.",{"fiber_yield":0.06,"survey_speed":0.02}),
		_entry("woven_carriers","Woven Carriers","Materials",90,0.007,["cordage","fiber_grading"],[_r("Fiber Plants","accessible")],["fiber","storage","travel"],"Fitted baskets and slings let one carrier move more while keeping both hands free.",{"haul_capacity":0.10,"dry_storage":0.04,"travel_speed":0.02}),
		_entry("rope_rigging","Rope Rigging","Infrastructure",420,0.004,["woven_carriers","standard_measures"],[_r("Fiber Plants","developed"),_r("Timber","developed")],["fiber","construction","travel"],"Standard ropes, blocks, and lifting teams make heavy loads controllable.",{"haul_capacity":0.16,"construction_rate":0.07,"mine_safety":0.04,"naval_capacity":0.04}),
		_entry("clay_testing","Clay Testing","Materials",80,0.008,[],[_r("Clay","recognized")],["clay","crafting"],"Small samples reveal which clays crack, shrink, seal, or endure heat.",{"survey_speed":0.03,"clay_yield":0.04}),
		_entry("clay_tempering","Tempered Clay","Materials",180,0.006,["clay_shaping","clay_testing"],[_r("Clay","accessible")],["clay","crafting"],"Sand, crushed shell, and old pottery control cracking as vessels dry.",{"container_capacity":0.08,"storage_loss":-0.03,"craft_output":0.04}),
		_entry("sealed_vessels","Sealed Vessels","Sustenance",330,0.005,["clay_tempering"],[_r("Clay","developed")],["clay","storage","food"],"Fitted lids and treated surfaces protect water, grain, oils, and medicines from damp and pests.",{"food_storage":0.10,"food_spoilage":-0.08,"health_protection":0.03,"trade_capacity":0.03}),
		_entry("kiln_control","Controlled Kilns","Materials",720,0.004,["pit_firing","clay_tempering"],[_r("Clay","developed"),_r("Timber","developed")],["clay","fire","crafting"],"Enclosed firing chambers make heat repeatable enough to reproduce strong ceramics.",{"craft_output":0.09,"fuel_efficiency":0.05,"container_capacity":0.08,"knowledge_rate":0.02}),
		_entry("quarry_reading","Reading the Quarry Face","Nature",280,0.005,["stone_sorting"],[_r("Stone","surveyed")],["stone","survey"],"Natural seams reveal where stone can be separated with less breakage and danger.",{"stone_yield":0.08,"mine_safety":0.03,"survey_speed":0.03}),
		_entry("wedges_and_levers","Wedges and Levers","Infrastructure",600,0.004,["hafted_tools","quarry_reading"],[_r("Stone","accessible"),_r("Timber","developed")],["stone","construction"],"Coordinated wedges and levers turn human effort into controlled movement of heavy stone.",{"stone_yield":0.10,"haul_capacity":0.06,"construction_rate":0.06}),
		_entry("lime_burning","Lime Burning","Materials",1800,0.003,["kiln_control"],[_r("Limestone","accessible")],["limestone","fire","construction"],"Burned limestone becomes a reactive powder that binds, coats, disinfects, and alters soil.",{"construction_rate":0.08,"health_protection":0.03,"soil_productivity":0.03}),
		_entry("lime_mortar","Lime Mortar","Infrastructure",2600,0.0028,["lime_burning","standard_measures"],[_r("Limestone","developed"),_r("Fine Sand","accessible")],["construction","materials"],"Measured lime, sand, and water produce joints that harden into enduring masonry.",{"housing_output":0.12,"construction_rate":0.10,"disaster_resilience":0.06,"state_capacity":0.02}),
		_entry("salt_working","Salt Working","Sustenance",900,0.004,["sealed_vessels"],[_r("Salt","surveyed")],["salt","food","storage"],"Evaporation and scraping turn saline earth or water into a dependable preservative.",{"food_spoilage":-0.08,"trade_capacity":0.06,"health_protection":0.01}),
		_entry("curing_regimens","Curing Regimens","Sustenance",1500,0.0035,["salt_working","smoking"],[_r("Salt","accessible")],["salt","food","storage"],"Measured salt, smoke, time, and airflow make preservation predictable across seasons.",{"food_spoilage":-0.12,"food_storage":0.07,"logistics_endurance":0.06}),
		_entry("peat_drying","Peat Drying","Materials",1500,0.004,["food_drying"],[_r("Peat","recognized")],["peat","fire","storage"],"Cut peat stacked above wet ground becomes a compact, transportable fuel.",{"fuel_efficiency":0.05,"timber_pressure":-0.03}),
		_entry("ore_assaying","Comparative Ore Assay","Materials",3300,0.0035,["kiln_control","standard_measures"],[_r("Copper Ore","surveyed")],["materials","fire","survey"],"Crushed samples, controlled heat, and recorded outcomes distinguish promising ore from colorful stone.",{"survey_speed":0.06,"metal_yield":0.04,"knowledge_rate":0.02}),
		_entry("copper_smelting","Copper Smelting","Materials",4400,0.0028,["ore_assaying","charcoal"],[_r("Copper Ore","accessible")],["materials","fire","crafting"],"Hot charcoal and carefully selected ore yield beads of workable metal.",{"tool_quality":0.08,"craft_output":0.07,"trade_capacity":0.04,"pollution":0.01}),
		_entry("copper_casting","Reusable Casting","Materials",6000,0.0025,["copper_smelting","clay_tempering"],[_r("Copper Ore","developed"),_r("Clay","developed")],["materials","crafting"],"Prepared molds make metal forms repeatable, divisible, and repairable.",{"tool_quality":0.08,"craft_output":0.10,"standardization":0.04,"warfare_readiness":0.04}),
		_entry("bronze_alloying","Bronze Alloying","Materials",8200,0.0022,["copper_casting"],[_r("Copper Ore","developed"),_r("Tin Ore","accessible")],["materials","trade","crafting"],"Copper and tin in controlled proportions produce a harder, more reliable material.",{"tool_quality":0.14,"construction_rate":0.05,"warfare_readiness":0.09,"trade_capacity":0.07}),
		_entry("mine_shoring","Timbered Mine Shoring","Infrastructure",10000,0.0024,["framed_construction","rope_rigging"],[_r("Timber","developed"),_r("Copper Ore","developed")],["infrastructure","timber","materials"],"Regular supports and inspection practices let workings extend beyond self-supporting ground.",{"mine_safety":0.12,"metal_yield":0.08,"construction_rate":0.03}),
		_entry("mine_drainage","Mine Drainage","Infrastructure",13000,0.0021,["mine_shoring","well_siting"],[_r("Deep Aquifer","recognized")],["infrastructure","water","materials"],"Sumps, channels, and lifting chains keep deeper workings usable.",{"mine_safety":0.08,"metal_yield":0.07,"water_access":0.04}),
		_entry("bitumen_sealing","Bitumen Sealing","Infrastructure",6500,0.0028,["sealed_vessels"],[_r("Bitumen","accessible")],["construction","travel","storage"],"Heated bitumen seals roofs, containers, hulls, and vulnerable road surfaces.",{"food_spoilage":-0.03,"housing_output":0.05,"naval_capacity":0.06,"route_speed":0.05}),
		_entry("iron_assaying","Iron Ore Assay","Materials",15500,0.0020,["kiln_control","standard_measures"],[_r("Iron Ore","surveyed")],["materials","fire","survey"],"Heated samples and slag behavior reveal iron-bearing rock that appearance alone concealed.",{"survey_speed":0.05,"metal_yield":0.04}),
		_entry("bloomery_smelting","Bloomery Smelting","Materials",18000,0.0018,["iron_assaying","charcoal","framed_construction"],[_r("Iron Ore","accessible")],["materials","fire","crafting"],"Forced air and charcoal reduce iron ore into a spongy bloom that can be consolidated by hammering.",{"tool_quality":0.12,"craft_output":0.08,"warfare_readiness":0.07,"pollution":0.02}),
		_entry("forge_welding","Forge Welding","Materials",22000,0.0016,["bloomery_smelting","standard_measures"],[_r("Iron Ore","developed")],["materials","crafting"],"Controlled heat and repeated working join iron pieces without melting them.",{"tool_quality":0.11,"construction_rate":0.07,"repair_capacity":0.08}),
		_entry("hardened_edges","Hardened Iron Edges","Materials",27000,0.0014,["forge_welding"],[_r("Iron Ore","developed")],["materials","crafting","warfare"],"Carbon, heat, and cooling are manipulated to keep cutting edges hard without making whole tools brittle.",{"tool_quality":0.16,"extraction_yield":0.10,"soil_productivity":0.05,"warfare_readiness":0.10}),
		_entry("coal_grading","Coal Grading","Nature",20500,0.0018,["quarry_reading","framed_construction"],[_r("Coal","surveyed")],["coal","survey","fire"],"Different black seams are classified by smoke, heat, ash, and behavior under pressure.",{"fuel_efficiency":0.08,"survey_speed":0.03}),
		_entry("coke_firing","Coke Firing","Materials",30000,0.0013,["coal_grading","kiln_control"],[_r("Coal","accessible")],["coal","fire","materials"],"Coal heated away from air produces a stronger, cleaner metallurgical fuel.",{"fuel_efficiency":0.12,"metal_yield":0.10,"timber_pressure":-0.06,"pollution":0.03}),
		_entry("refractory_furnaces","Refractory Furnaces","Materials",35000,0.0012,["coke_firing"],[_r("Refractory Clay","accessible")],["materials","fire","crafting"],"Heat-resistant linings allow furnaces to remain hotter and operate longer without collapsing.",{"fuel_efficiency":0.10,"metal_yield":0.12,"craft_output":0.08}),
		_entry("blast_furnace","Continuous Blast Furnace","Materials",41000,0.0010,["refractory_furnaces","mine_drainage","rope_rigging"],[_r("Iron Ore","developed"),_r("Coal","developed"),_r("Limestone","developed")],["materials","infrastructure","fire"],"Continuous high-temperature reduction transforms the scale and organization of iron production.",{"metal_yield":0.22,"tool_quality":0.16,"construction_rate":0.10,"state_capacity":0.05,"pollution":0.08}),
		_entry("sulfur_purification","Sulfur Purification","Materials",26000,0.0015,["sealed_vessels","kiln_control","standard_measures"],[_r("Sulfur","accessible")],["materials","nature","crafting"],"Controlled melting and condensation separate sulfur from mineral impurities.",{"chemical_control":0.08,"health_risk":0.01}),
		_entry("nitrate_cultivation","Nitrate Beds","Nature",31000,0.0013,["tallies","sealed_vessels"],[_r("Nitrates","recognized")],["nature","materials","storage"],"Organic waste, drainage, and time are managed to cultivate nitrate-rich earth.",{"soil_productivity":0.05,"chemical_control":0.07,"sanitation":-0.01}),
		_entry("black_powder","Composite Propellant","Warfare",39000,0.0009,["sulfur_purification","nitrate_cultivation","charcoal"],[_r("Sulfur","developed"),_r("Nitrates","developed")],["materials","warfare","crafting"],"Purified sulfur, charcoal, and nitrates are combined in repeatable proportions with violently expanding results.",{"warfare_readiness":0.18,"mining_output":0.10,"state_capacity":0.03,"disaster_risk":0.04}),
		_entry("phosphate_dressing","Phosphate Dressing","Sustenance",45500,0.0010,["lime_burning","standard_measures"],[_r("Phosphate Rock","accessible")],["sustenance","nature","materials"],"Ground phosphate is tested against exhausted soils and selected crops.",{"soil_productivity":0.14,"food_output":0.08,"water_pollution":0.02}),
		_entry("graphite_marking","Graphite Marking","Information",49000,0.0011,["standard_measures"],[_r("Graphite","accessible")],["information","materials","administration"],"Prepared graphite leaves compact, erasable marks suited to inventories, diagrams, and calculation.",{"knowledge_rate":0.10,"state_capacity":0.06,"standardization":0.04}),
		_entry("graphite_crucibles","Graphite Crucibles","Materials",52500,0.0009,["graphite_marking","refractory_furnaces"],[_r("Graphite","developed"),_r("Refractory Clay","developed")],["materials","fire","crafting"],"Graphite-bearing crucibles endure heat and protect molten material from contamination.",{"metal_yield":0.10,"craft_output":0.08,"chemical_control":0.05}),
		_entry("material_accounting","Material Accounting","Information",1200,0.0038,["tallies"],[],["storage","administration","trade"],"Stores are recorded by source, quality, loss, obligation, and intended use rather than as a single heap.",{"storage_loss":-0.03,"haul_capacity":0.03,"state_capacity":0.03}),
		_entry("workshop_standards","Workshop Standards","Information",9000,0.0022,["standard_measures","material_accounting"],[],["crafting","administration","materials"],"Patterns, tolerances, and named grades let knowledge survive individual makers.",{"craft_output":0.09,"repair_capacity":0.06,"knowledge_rate":0.04,"standardization":0.08})
	]

static func _r(resource_name: String, stage: String, minimum_stock := 0.0) -> Dictionary:
	return {"resource":resource_name,"stage":stage,"minimum_stock":minimum_stock}

static func _entry(id: String,name: String,direction: String,day: int,chance: float,requires: Array,resource_requirements: Array,signals: Array,observation: String,effects: Dictionary) -> Dictionary:
	return {"id":id,"name":name,"direction":direction,"chance":chance,"day":day,"requires":requires,"resource_requirements":resource_requirements,"signals":signals,"observation":observation,"effects":effects}
