extends RefCounted

# Invisible social, medical, informational, agricultural, infrastructural, and
# military possibilities across roughly two centuries. These are not displayed
# as a selectable tree. Conditions, work, materials, attention, and chance decide
# which historical path becomes real.

static func entries()->Array[Dictionary]:
	return [
		# Sustenance and land use
		_e("crop_calendars","Crop Calendars","Sustenance",240,0.0045,["seasonal_patterns","seed_selection"],["food","nature","administration"],"Planting and harvest dates are preserved across households instead of remembered separately.",{"cultivation_yield":0.08,"task_coordination":0.03,"knowledge_preservation":0.02}),
		_e("managed_fallow","Managed Fallow","Sustenance",900,0.0035,["crop_calendars"],["food","nature"],"Leaving selected ground uncultivated restores yields more reliably than abandoning fields at random.",{"soil_productivity":0.09,"ecology_recovery":0.05,"food_output":0.02}),
		_e("seed_reserves","Protected Seed Reserves","Sustenance",1250,0.0032,["seed_selection","public_stores"],["food","storage","administration"],"The best seed is separated from ordinary food stores and protected through lean seasons.",{"cultivation_yield":0.07,"food_storage":0.04,"state_capacity":0.02}),
		_e("irrigation_schedules","Irrigation Schedules","Sustenance",2600,0.0028,["crop_calendars","drainage","tallies"],["food","freshwater","construction"],"Households coordinate water turns so upstream use no longer destroys downstream crops.",{"cultivation_yield":0.12,"soil_productivity":0.04,"state_capacity":0.04,"labor_demand":0.03,"disease_exposure":0.015}),
		_e("crop_rotation","Crop Rotation","Sustenance",6200,0.0022,["managed_fallow","standard_measures"],["food","nature","information"],"Different crops are sequenced to preserve soil and disrupt recurring pests.",{"cultivation_yield":0.12,"soil_productivity":0.10,"ecology_recovery":0.03,"knowledge_rate":0.02}),
		_e("grain_milling","Rotary Grain Milling","Sustenance",4800,0.0025,["hafted_tools","standard_measures"],["food","crafting","construction"],"Rotary stones convert stored grain into digestible flour with less labor.",{"food_output":0.06,"labor_efficiency":0.04,"tool_quality":0.03,"injury_risk":0.006}),
		_e("fermentation_control","Controlled Fermentation","Sustenance",7200,0.0020,["sealed_vessels","standard_measures"],["food","storage","health"],"Temperature, vessels, and starter cultures are managed to reproduce fermentation.",{"food_spoilage":-0.07,"nutrition_quality":0.04,"water_safety":0.03,"health_risk":0.005}),
		_e("regional_granaries","Regional Granaries","Sustenance",15000,0.0015,["seed_reserves","material_accounting","framed_construction"],["food","storage","administration"],"Surplus is distributed among measured, inspected stores rather than concentrated in one vulnerable reserve.",{"food_storage":0.18,"food_spoilage":-0.06,"state_capacity":0.05,"cohesion":0.02,"labor_demand":0.02}),
		_e("soil_assays","Comparative Soil Assays","Nature",23500,0.0013,["crop_rotation","standard_measures"],["nature","food","materials"],"Soils are compared by drainage, texture, crop response, and amendments rather than color alone.",{"soil_productivity":0.08,"observation_rate":0.05,"cultivation_yield":0.04}),
		_e("intensive_gardens","Intensive Market Gardens","Sustenance",36000,0.0010,["soil_assays","irrigation_schedules","regional_granaries"],["food","trade","administration"],"Highly tended plots near settlements produce diverse perishables for dense populations.",{"food_output":0.12,"nutrition_quality":0.08,"trade_capacity":0.04,"labor_demand":0.05,"ecological_pressure":0.03}),

		# Health, reproduction, sanitation, and care
		_e("birth_attendants","Experienced Birth Attendants","Health",320,0.0042,["wound_cleaning"],["health","population","freshwater"],"Birth attendants preserve positioning, cleanliness, warning signs, and methods of assisting difficult labor.",{"maternal_safety":0.10,"neonatal_survival":0.06,"knowledge_preservation":0.02,"labor_demand":0.01}),
		_e("latrine_siting","Latrine Siting","Health",700,0.0040,["drainage","clean_water"],["health","construction","freshwater"],"Waste pits are placed according to slope, water flow, soil, and settlement use.",{"sanitation":0.10,"disease_exposure":-0.08,"water_safety":0.04,"labor_demand":0.01}),
		_e("isolation_practice","Isolation Practice","Health",1300,0.0030,["herbal_classification","labor_rotations"],["illness","administration","health"],"Repeated outbreaks reveal that separating the visibly ill can interrupt some chains of sickness.",{"disease_exposure":-0.10,"health_protection":0.04,"labor_demand":0.03,"cohesion":-0.015}),
		_e("case_records","Medical Case Records","Health",3100,0.0025,["herbal_classification","tallies"],["health","information","illness"],"Treatments and outcomes are recorded together, exposing remedies that fail as well as those that help.",{"knowledge_rate":0.06,"health_protection":0.05,"knowledge_preservation":0.05,"labor_demand":0.015}),
		_e("trained_midwives","Trained Midwives","Health",5600,0.0020,["birth_attendants","case_records","standard_measures"],["health","education","population"],"Birth knowledge is taught deliberately and evaluated through recorded outcomes.",{"maternal_safety":0.14,"neonatal_survival":0.12,"conception_support":0.02,"state_capacity":0.02,"labor_demand":0.015}),
		_e("public_baths","Public Washing Facilities","Health",8500,0.0018,["latrine_siting","well_siting","lime_burning"],["health","construction","freshwater"],"Shared water and washing facilities separate drinking, cleaning, animals, and waste.",{"sanitation":0.12,"disease_exposure":-0.08,"health_protection":0.04,"construction_rate":0.02,"labor_demand":0.025}),
		_e("surgical_anatomy","Surgical Anatomy","Health",18000,0.0012,["case_records","standard_measures"],["health","information","injury"],"Anatomical observations are compared across injuries and deaths, replacing many inherited assumptions.",{"injury_risk":-0.10,"maternal_safety":0.05,"knowledge_rate":0.06,"health_risk":0.01}),
		_e("civic_infirmaries","Civic Infirmaries","Health",25000,0.0010,["surgical_anatomy","public_stores","trained_midwives"],["health","administration","construction"],"Dedicated institutions concentrate carers, records, clean supplies, and difficult cases.",{"health_protection":0.10,"maternal_safety":0.08,"neonatal_survival":0.06,"state_capacity":0.04,"labor_demand":0.04,"disease_exposure":0.01}),
		_e("contagion_mapping","Contagion Mapping","Health",41000,0.0008,["case_records","census_rolls","regional_maps"],["health","information","administration"],"Cases are mapped through households, water, work, and movement to distinguish environmental from contagious illness.",{"disease_exposure":-0.16,"observation_rate":0.08,"state_capacity":0.04,"institutional_rigidity":-0.02}),
		_e("preventive_inoculation","Preventive Inoculation","Health",56000,0.00065,["contagion_mapping","experimental_controls"],["health","population","administration"],"Controlled exposure is organized to reduce the danger of later epidemics, despite immediate individual risk.",{"disease_exposure":-0.20,"neonatal_survival":0.05,"state_capacity":0.04,"health_risk":0.015,"legitimacy":-0.01}),

		# Information, collective intelligence, and scientific method
		_e("pictographic_records","Pictographic Records","Information",420,0.0040,["tallies"],["information","administration","storage"],"Marks begin preserving categories, events, and obligations rather than quantities alone.",{"knowledge_preservation":0.10,"state_capacity":0.04,"task_coordination":0.03,"labor_demand":0.015}),
		_e("place_value","Place-Value Calculation","Information",1900,0.0028,["standard_measures","pictographic_records"],["information","trade","construction"],"Written position carries numerical meaning, making large calculations compact and checkable.",{"standardization":0.08,"knowledge_rate":0.05,"trade_capacity":0.04,"construction_rate":0.02}),
		_e("phonetic_notation","Phonetic Notation","Information",3400,0.0023,["pictographic_records"],["information","education","administration"],"Written signs represent speech sounds, allowing names and unfamiliar words to be preserved.",{"knowledge_preservation":0.14,"adoption_rate":0.05,"state_capacity":0.05,"labor_demand":0.02}),
		_e("formal_archives","Formal Archives","Information",5900,0.0020,["phonetic_notation","public_stores"],["information","administration","construction"],"Records receive durable copies, custodians, dates, and known places of storage.",{"knowledge_preservation":0.16,"state_capacity":0.08,"institutional_rigidity":0.02,"labor_demand":0.025}),
		_e("geometric_survey","Geometric Survey","Information",7600,0.0018,["place_value","standard_measures"],["information","survey","construction"],"Angles, baselines, and repeatable procedures turn land measurement into geometry.",{"survey_speed":0.12,"construction_rate":0.06,"state_capacity":0.04,"trade_capacity":0.02}),
		_e("regional_maps","Regional Maps","Information",11000,0.0016,["geometric_survey","route_memory"],["information","travel","survey"],"Routes, settlements, waters, elevations, and borders are reconciled onto shared surfaces.",{"route_speed":0.10,"survey_speed":0.09,"state_capacity":0.04,"warfare_readiness":0.03}),
		_e("public_schools","Public Instruction","Information",17500,0.0013,["formal_archives","customary_law"],["education","administration","society"],"Teaching is organized beyond households and occupations, widening access to preserved knowledge.",{"adoption_rate":0.13,"knowledge_rate":0.10,"knowledge_preservation":0.06,"state_capacity":0.04,"labor_demand":0.04}),
		_e("paper_making","Sheet Fiber Writing Material","Information",22000,0.0011,["fiber_grading","kiln_control","formal_archives"],["fiber","information","crafting"],"Pulped fibers are formed into light sheets suitable for dense records and wide circulation.",{"knowledge_preservation":0.12,"adoption_rate":0.08,"trade_capacity":0.03,"timber_pressure":0.02}),
		_e("printing_process","Repeatable Printing","Information",33000,0.0009,["paper_making","workshop_standards","graphite_marking"],["information","crafting","education"],"Reusable forms reproduce texts and diagrams faster than individual copying.",{"adoption_rate":0.18,"knowledge_rate":0.13,"knowledge_preservation":0.10,"institutional_rigidity":-0.02,"labor_demand":0.025}),
		_e("experimental_controls","Experimental Controls","Information",39000,0.0008,["case_records","workshop_standards","place_value"],["information","nature","health"],"Investigators deliberately vary one condition while holding others stable and preserve failed trials.",{"observation_rate":0.16,"knowledge_rate":0.15,"standardization":0.05,"health_risk":0.008}),
		_e("statistical_inference","Statistical Inference","Information",59000,0.0006,["experimental_controls","census_rolls"],["information","administration","health"],"Variation across many observations is measured rather than dismissed as noise.",{"observation_rate":0.14,"knowledge_rate":0.13,"state_capacity":0.07,"health_protection":0.03}),

		# Institutions, coordination, law, finance, and culture
		_e("household_councils","Household Councils","Society",260,0.0045,["labor_rotations"],["society","dispute","administration"],"Households send recognized speakers to settle shared work and recurring disputes.",{"cohesion":0.07,"legitimacy":0.04,"state_capacity":0.03,"labor_demand":0.015}),
		_e("census_rolls","Household Census Rolls","Society",1800,0.0028,["pictographic_records","household_councils"],["population","administration","information"],"Households, ages, dependents, occupations, and obligations are counted by name.",{"state_capacity":0.10,"task_coordination":0.05,"knowledge_preservation":0.03,"institutional_rigidity":0.015,"labor_demand":0.025}),
		_e("public_levies","Scheduled Public Levies","Society",4200,0.0021,["census_rolls","customary_law"],["administration","construction","society"],"Public labor and material obligations become scheduled, recorded, and appealable.",{"state_capacity":0.11,"construction_rate":0.05,"legitimacy":0.02,"cohesion":-0.01,"labor_demand":0.035}),
		_e("specialized_courts","Specialized Courts","Society",8700,0.0017,["formal_archives","customary_law","census_rolls"],["law","administration","trade"],"Different disputes are heard through preserved procedures by people trained for the matter.",{"legitimacy":0.08,"state_capacity":0.08,"trade_capacity":0.04,"institutional_rigidity":0.025,"labor_demand":0.025}),
		_e("property_registers","Property Registers","Society",12500,0.0015,["geometric_survey","specialized_courts"],["law","trade","survey"],"Claims to fields, water, workshops, and buildings are tied to maps and archived decisions.",{"trade_capacity":0.09,"state_capacity":0.08,"legitimacy":0.03,"cohesion":-0.015,"institutional_rigidity":0.025}),
		_e("craft_guilds","Craft Guilds","Society",16000,0.0013,["workshop_standards","specialized_courts"],["crafting","society","trade"],"Makers regulate apprenticeship, quality, mutual aid, and access to specialized work.",{"craft_output":0.10,"standardization":0.08,"adoption_rate":0.05,"institutional_rigidity":0.035,"trade_capacity":0.04}),
		_e("public_credit","Public Credit","Society",27000,0.0010,["material_accounting","property_registers","regional_granaries"],["trade","administration","construction"],"Future tax and store revenues support present projects through recorded obligations.",{"state_capacity":0.12,"construction_rate":0.08,"trade_capacity":0.10,"legitimacy":-0.015,"institutional_rigidity":0.02}),
		_e("risk_pools","Mutual Risk Pools","Society",35000,0.0009,["public_credit","statistical_inference"],["trade","society","information"],"Many households contribute to reserves that absorb rare fires, deaths, wrecks, and failed harvests.",{"disaster_resilience":0.12,"cohesion":0.05,"trade_capacity":0.06,"state_capacity":0.04,"labor_demand":0.02}),
		_e("professional_service","Professional Civil Service","Society",47000,0.0007,["public_schools","specialized_courts","public_credit"],["administration","education","law"],"Offices preserve procedures and train successors independently of individual rulers.",{"state_capacity":0.18,"task_coordination":0.10,"knowledge_preservation":0.06,"institutional_rigidity":0.06,"labor_demand":0.05}),

		# Infrastructure, movement, energy, and urban systems
		_e("graded_roads","Graded Roads","Infrastructure",1400,0.0030,["route_memory","drainage","labor_rotations"],["travel","construction","logistics"],"Road surfaces are crowned, drained, and repaired according to traffic and terrain.",{"route_speed":0.12,"haul_capacity":0.07,"construction_rate":0.03,"labor_demand":0.025,"ecological_pressure":0.01}),
		_e("timber_bridges","Timber Bridges","Infrastructure",3600,0.0024,["framed_construction","rope_rigging","graded_roads"],["travel","timber","construction"],"Standard trusses carry roads across water and unstable ground.",{"route_speed":0.10,"haul_capacity":0.05,"disaster_resilience":0.03,"timber_pressure":0.025}),
		_e("canal_locks","Canal Locks","Infrastructure",11800,0.0015,["irrigation_schedules","geometric_survey","lime_mortar"],["water","construction","logistics"],"Gated chambers raise and lower vessels between controlled water levels.",{"haul_capacity":0.16,"trade_capacity":0.10,"state_capacity":0.04,"labor_demand":0.04,"disease_exposure":0.01}),
		_e("water_mills","Water-Powered Mills","Infrastructure",14500,0.0014,["grain_milling","geometric_survey","framed_construction"],["water","crafting","construction"],"Controlled water flow supplies continuous rotary power to milling and workshops.",{"food_output":0.07,"craft_output":0.10,"labor_efficiency":0.05,"construction_rate":0.03,"ecological_pressure":0.02}),
		_e("urban_street_plans","Urban Street Plans","Infrastructure",20500,0.0012,["regional_maps","public_levies","lime_mortar"],["construction","administration","health"],"Growth corridors, markets, drainage, firebreaks, and public ways are reserved before building closes them.",{"construction_rate":0.08,"route_speed":0.05,"sanitation":0.04,"state_capacity":0.04,"institutional_rigidity":0.02}),
		_e("covered_sewers","Covered Sewers","Infrastructure",30500,0.0009,["urban_street_plans","public_baths","lime_mortar"],["health","construction","water"],"Enclosed channels move waste away from dense settlement while inspection points permit maintenance.",{"sanitation":0.18,"disease_exposure":-0.12,"water_safety":0.06,"construction_rate":0.03,"labor_demand":0.04}),
		_e("precision_machinery","Precision Machinery","Infrastructure",51500,0.00065,["blast_furnace","workshop_standards","place_value"],["crafting","materials","information"],"Measured components, bearings, guides, and cutting tools reproduce controlled motion.",{"craft_output":0.18,"tool_quality":0.16,"repair_capacity":0.10,"standardization":0.09,"labor_demand":0.03}),

		# Security, military organization, and coercive capacity
		_e("field_fortifications","Field Fortifications","Warfare",1100,0.0032,["watch_rotation","drainage"],["defense","construction","danger"],"Ditches, stakes, banks, and controlled approaches turn temporary camps into defensible ground.",{"warfare_readiness":0.09,"security_efficiency":0.06,"construction_rate":0.02,"labor_demand":0.025}),
		_e("fortified_stores","Fortified Stores","Warfare",3900,0.0023,["field_fortifications","public_stores","framed_construction"],["defense","storage","construction"],"Critical reserves are separated, guarded, fire-protected, and designed to resist seizure.",{"food_storage":0.05,"disaster_resilience":0.06,"security_efficiency":0.08,"state_capacity":0.03,"labor_demand":0.02}),
		_e("siege_engineering","Siege Engineering","Warfare",9200,0.0017,["rope_rigging","geometric_survey","formation_drill"],["warfare","construction","materials"],"Measured frames, counterweights, protective works, and supply schedules organize attacks on fortifications.",{"warfare_readiness":0.14,"construction_rate":0.04,"haul_capacity":0.03,"labor_demand":0.035,"timber_pressure":0.025}),
		_e("professional_corps","Professional Military Corps","Warfare",15500,0.0013,["supply_groups","census_rolls","public_levies"],["warfare","administration","training"],"A permanent body trains, records equipment, maintains readiness, and preserves doctrine.",{"warfare_readiness":0.16,"security_efficiency":0.10,"state_capacity":0.04,"labor_demand":0.06,"legitimacy":-0.01}),
		_e("military_staffs","Military Staff Planning","Warfare",28500,0.0010,["professional_corps","regional_maps","formal_archives"],["warfare","information","logistics"],"Specialized officers reconcile intelligence, movement, stores, terrain, and timing before orders are issued.",{"warfare_readiness":0.15,"logistics_endurance":0.09,"task_coordination":0.08,"state_capacity":0.04,"institutional_rigidity":0.02}),
		_e("battlefield_medicine","Battlefield Medicine","Warfare",32500,0.0009,["civic_infirmaries","professional_corps"],["warfare","health","logistics"],"Triage, evacuation, clean instruments, and organized convalescence reduce deaths after injury.",{"injury_risk":-0.14,"health_protection":0.05,"logistics_endurance":0.03,"labor_demand":0.025}),
		_e("powder_artillery","Powder Artillery","Warfare",45000,0.0007,["black_powder","precision_machinery","military_staffs"],["warfare","materials","crafting"],"Controlled powder charges propel standardized projectiles from reinforced barrels.",{"warfare_readiness":0.24,"state_capacity":0.05,"craft_output":0.04,"pollution":0.04,"disaster_risk":0.05,"labor_demand":0.04})
	]

static func _e(id:String,name:String,direction:String,day:int,chance:float,requires:Array,signals:Array,observation:String,effects:Dictionary)->Dictionary:
	return {"id":id,"name":name,"direction":direction,"day":day,"chance":chance,"requires":requires,"signals":signals,"observation":observation,"effects":effects}
