extends RefCounted

# Distinct authored practices with causal prerequisites and real simulation effects.
static func entries()->Array[Dictionary]:
	return [
		{"id": "festival_calendar", "name": "Festival Calendar", "dynamic": "culture", "subcategory": "Social cohesion", "direction": "culture", "day": 180, "requires": ["seasonal_patterns"], "observation": "Seasonal gatherings coordinate shared labor and bring scattered households together.", "effects": {"cohesion": 0.06, "task_coordination": 0.025}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "oral_epics", "name": "Oral Epics", "dynamic": "culture", "subcategory": "Collective memory", "direction": "culture", "day": 90, "requires": [], "observation": "Trained reciters preserve long accounts through rhythm, performance, and correction by listeners.", "effects": {"knowledge_preservation": 0.05, "cohesion": 0.04}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "public_theatre", "name": "Public Theatre", "dynamic": "culture", "subcategory": "Inquiry breadth", "direction": "culture", "day": 2500, "requires": ["oral_epics", "framed_construction"], "observation": "Dedicated performance spaces bring stories, criticism, and public argument to larger audiences.", "effects": {"cohesion": 0.06, "adoption_rate": 0.06, "labor_demand": 0.015}, "chance": 0.002, "signals": ["research", "administration", "construction"]},
		{"id": "civic_games", "name": "Civic Games", "dynamic": "culture", "subcategory": "Shared legitimacy", "direction": "culture", "day": 1200, "requires": ["festival_calendar", "standard_measures"], "observation": "Agreed rules and measured contests create shared occasions across settlement rivalries.", "effects": {"cohesion": 0.07, "legitimacy": 0.035, "labor_demand": 0.01}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "comparative_chronicles", "name": "Comparative Chronicles", "dynamic": "culture", "subcategory": "Collective memory", "direction": "culture", "day": 9000, "requires": ["oral_epics", "formal_archives"], "observation": "Competing written accounts are checked against dates and records rather than repeating one official memory.", "effects": {"knowledge_preservation": 0.09, "observation_rate": 0.05, "institutional_rigidity": -0.02}, "chance": 0.002, "signals": ["research", "administration", "construction"]},
		{"id": "public_libraries", "name": "Public Libraries", "dynamic": "culture", "subcategory": "Inquiry breadth", "direction": "culture", "day": 34000, "requires": ["printing_process", "public_schools"], "observation": "Catalogued shared collections let readers outside elite households compare and teach competing ideas.", "effects": {"adoption_rate": 0.12, "knowledge_rate": 0.08, "labor_demand": 0.025}, "chance": 0.002, "signals": ["research", "administration", "construction"]},
		{"id": "crew_handoffs", "name": "Crew Handoffs", "dynamic": "labor", "subcategory": "Coordination", "direction": "labor", "day": 90, "requires": ["labor_rotations"], "observation": "Checked tallies let the next crew continue unfinished work without duplicating the previous shift.", "effects": {"task_coordination": 0.07, "storage_loss": -0.025}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "apprentice_contracts", "name": "Apprentice Contracts", "dynamic": "labor", "subcategory": "Able workforce", "direction": "labor", "day": 1100, "requires": ["customary_law", "hafted_tools"], "observation": "Agreed training duties and demonstrations of competence preserve skilled work across generations.", "effects": {"craft_output": 0.07, "adoption_rate": 0.045}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "work_rest_limits", "name": "Work and Rest Limits", "dynamic": "labor", "subcategory": "Workload balance", "direction": "labor", "day": 600, "requires": ["labor_rotations", "wound_cleaning"], "observation": "Comparing fatigue and injury sets limits on continuous work, trading immediate hours for sustained output.", "effects": {"fatigue": -0.08, "injury_risk": -0.045, "labor_demand": 0.015}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "work_motion_studies", "name": "Work Motion Studies", "dynamic": "labor", "subcategory": "Work efficiency", "direction": "labor", "day": 28000, "requires": ["experimental_controls", "workshop_standards"], "observation": "Measured comparisons of tool placement and repeated movements reduce wasted effort at workshops.", "effects": {"labor_efficiency": 0.1, "task_coordination": 0.055}, "chance": 0.002, "signals": ["research", "administration", "construction"]},
		{"id": "shared_childcare", "name": "Shared Childcare", "dynamic": "demography", "subcategory": "Child survival", "direction": "demography", "day": 180, "requires": ["labor_rotations"], "observation": "Households share supervised care so children remain attended while caregivers rotate necessary work.", "effects": {"neonatal_survival": 0.05, "labor_efficiency": 0.025, "labor_demand": 0.01}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "maternal_recovery", "name": "Maternal Recovery Care", "dynamic": "demography", "subcategory": "Maternal safety", "direction": "demography", "day": 1100, "requires": ["birth_attendants", "shared_childcare"], "observation": "Food and relief from heavy work support recovery after birth rather than an immediate return to full workloads.", "effects": {"maternal_safety": 0.08, "conception_support": 0.035, "labor_demand": 0.02}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "child_growth_records", "name": "Child Growth Records", "dynamic": "demography", "subcategory": "Child survival", "direction": "demography", "day": 7000, "requires": ["case_records", "census_rolls"], "observation": "Repeated measurements reveal poor growth before severe illness and help direct scarce food and care.", "effects": {"neonatal_survival": 0.075, "nutrition_quality": 0.035}, "chance": 0.002, "signals": ["research", "administration", "construction"]},
		{"id": "household_space_planning", "name": "Household Space Planning", "dynamic": "demography", "subcategory": "Shelter capacity", "direction": "demography", "day": 2000, "requires": ["framed_construction", "shared_childcare"], "observation": "Sleeping space, ventilation, and care areas are planned around household needs rather than floor area alone.", "effects": {"housing_output": 0.075, "health_protection": 0.035}, "chance": 0.002, "signals": ["research", "administration", "construction"]},
		{"id": "wayfinding_stars", "name": "Celestial Wayfinding", "dynamic": "logistics", "subcategory": "Route quality", "direction": "logistics", "day": 800, "requires": ["seasonal_patterns", "route_memory"], "observation": "Recognized stars and seasonal sky changes help travelers keep direction when landmarks disappear.", "effects": {"route_speed": 0.055, "survey_speed": 0.055}, "chance": 0.005, "signals": ["research", "administration", "construction"]},
		{"id": "caravanserais", "name": "Caravanserais", "dynamic": "logistics", "subcategory": "Trade reach", "direction": "logistics", "day": 6500, "requires": ["graded_roads", "public_stores"], "observation": "Maintained stopping places offer shelter, protected stores, and rest along established overland trade routes.", "effects": {"logistics_endurance": 0.1, "trade_capacity": 0.075, "food_storage": 0.04, "labor_demand": 0.02}, "chance": 0.002, "signals": ["research", "administration", "construction"]},
		{"id": "counterweight_cranes", "name": "Counterweight Cranes", "dynamic": "logistics", "subcategory": "Carrying capacity", "direction": "logistics", "day": 11000, "requires": ["rope_rigging", "standard_measures", "framed_construction"], "observation": "Counterweights and controlled lifting tackle let crews handle heavier loads at transfer points.", "effects": {"haul_capacity": 0.14, "construction_rate": 0.05, "injury_risk": 0.01}, "chance": 0.002, "signals": ["research", "administration", "construction"]},
		{"id": "cargo_seals", "name": "Cargo Seals", "dynamic": "logistics", "subcategory": "Storage system", "direction": "logistics", "day": 1800, "requires": ["material_accounting", "clay_tempering"], "observation": "Marked seals allow comparison of dispatched and received cargo to identify losses along a route.", "effects": {"storage_loss": -0.065, "trade_capacity": 0.04, "state_capacity": 0.025}, "chance": 0.005, "signals": ["research", "administration", "construction"]}
	]
