extends SceneTree
func _initialize()->void:call_deferred("run")
func run()->void:
	var state=root.get_node("GameState");var direction=root.get_node("PeopleDirection")
	state.reset_for_new_world(89121);direction.reset_for_new_world()
	assert(load("res://scripts/people_direction_screen.gd").can_instantiate())
	assert(load("res://scripts/civilization_day.gd").can_instantiate())
	assert(load("res://scripts/save_system.gd").can_instantiate())
	var C=load("res://scripts/cultural_inheritance.gd")
	for century in 3:
		state.elapsed_days=century*36500
		assert(direction.choose("expansion").get("ok",false))
		assert(direction.choose("sustenance").has("error"))
	state.elapsed_days=109500;assert(direction.choose("sustenance").get("ok",false))
	assert(is_equal_approx(C.distribution(direction.cultural_memory,"ambition",109500).expansion,.75))
	assert(C.distribution(direction.cultural_memory,"ambition",109500,true).stewardship>.25)
	var scout=root.get_node("CivilizationSystem").scouting_staff
	assert(scout.data.share>0)
	scout.set_policy(.01,"exploration")
	assert(not direction.auto_scouting)
	direction.inclination_review_day=-1;direction.apply_inclinations(int(state.elapsed_days))
	assert(is_equal_approx(scout.data.share,.01))
	direction.set_delegated("scouting",true)
	assert(direction.auto_scouting and scout.data.share>.01)
	direction.set_delegated("research",false)
	var allocations:Dictionary=state.research_allocations.duplicate(true)
	direction.inclination_review_day=-1;direction.apply_inclinations(int(state.elapsed_days))
	assert(state.research_allocations==allocations)
	var expansion_bias:Dictionary=C.labor_bias(direction.cultural_memory,int(state.elapsed_days))
	assert(expansion_bias.get("Logistics",0)>0 and expansion_bias.get("Food",0)>0)
	var multiplier:float=direction.research_multiplier("logistics");assert(multiplier>.95 and multiplier<1.25)
	var before:Dictionary=direction.cultural_memory.duplicate(true)
	direction.advance(109510);direction.advance(109510)
	assert(direction.cultural_memory==before)
	for i in 20:direction.record_cultural_action("settlement:%d"%i,"expansion",2.0)
	assert(direction.cultural_memory.choices.expansion==35)
	assert(not direction.record_cultural_action("settlement:0","expansion",2.0))
	var saved:Dictionary=direction.export_state()
	assert(direction.import_state(bytes_to_var(var_to_bytes(saved))).get("ok",false))
	assert(direction.cultural_memory.choices.expansion==35)
	var broken:=saved.duplicate(true);broken.cultural_memory.recent.ambition.expansion=-1
	assert(direction.import_state(broken).has("error"))
	var legacy:=saved.duplicate(true);legacy.erase("cultural_memory");legacy.version=2
	assert(direction.import_state(legacy).get("ok",false));assert(direction.cultural_memory.events.size()==1)
	assert(direction.cultural_memory.choices.sustenance==10)
	state.elapsed_days=146000;assert(direction.choose("dominion").get("ok",false))
	assert(C.weight(direction.cultural_memory,"obligation","exploitation",146000)>0)
	var plan:Dictionary=load("res://scripts/civilization_controller.gd").current_plan("player")
	assert(plan.expansion_food>=45)
	var controller=load("res://scripts/civilization_controller.gd")
	var convoy_before:Dictionary=state.settlement_convoy.duplicate(true)
	plan.hungry=true;controller.expansion_orders("player",plan)
	assert(state.settlement_convoy==convoy_before)
	for choice in C.PROFILES:
		var memory:Dictionary=C.empty();assert(C.record(memory,"test",choice,0,10.0))
		assert(not C.labor_bias(memory,0).is_empty())
		assert(C.scout_share(memory,0)>0 and C.scout_share(memory,0)<=.10)
	print("CULTURE_INTEGRATION_CHOICE_WEIGHT_SAVE_MIGRATION_CAPS_OK")
	var output:=OS.get_environment("CULTURE_REVIEW_OUTPUT")
	if not output.is_empty():
		direction.import_state(saved);state.elapsed_days=146000;direction.choose("dominion")
		var screen=load("res://scripts/people_direction_screen.gd").new();root.add_child(screen);screen._show_page(2)
		root.content_scale_size=Vector2i(1200,900);root.content_scale_factor=1.0;root.size=Vector2i(1200,900)
		for i in 8:await process_frame
		await RenderingServer.frame_post_draw
		root.get_texture().get_image().save_png(output)
	quit()
